
package com.mycompany.feedgrow.vista;

import com.mycompany.feedgrow.controlador.BusquedaControlador;
import com.mycompany.feedgrow.modelo.Estudiante;
import com.mycompany.feedgrow.persistencia.GestorDatos;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

public class Busqueda extends JPanel {

    private final GestorDatos gestor;
    private final Estudiante usuario;

    public Busqueda( Estudiante usuario, GestorDatos gestor) {
        this.gestor = gestor;
        this.usuario = usuario;
        initComponents();
        initCustom();
        initLista();
    }

    private void initCustom() {
       
        listaEstudiantes.setLayout(
            new javax.swing.BoxLayout(listaEstudiantes, javax.swing.BoxLayout.Y_AXIS)
        );

        campoBusqueda.addActionListener(e -> ejecutarBusqueda());
    }
    private void initLista(){
      BusquedaControlador controlador = new BusquedaControlador();
      List<Estudiante> resultados = controlador.buscar("", "", usuario, gestor.getEstudiantes());
      listaEstudiantes.removeAll();
       for (Estudiante e : resultados) {
                ItemBusqueda item = new ItemBusqueda(this, usuario, e, gestor);
                listaEstudiantes.add(item);
            }
       listaEstudiantes.revalidate();
       listaEstudiantes.repaint();
    }

   private void ejecutarBusqueda() {
    BusquedaControlador controlador = new BusquedaControlador();
    String nombre = campoBusqueda.getText().trim();
    String carrera = (String) jSeleccionadorDeCarrera.getSelectedItem();

    List<Estudiante> resultados = controlador.buscar(nombre, carrera, usuario, gestor.getEstudiantes());
    listaEstudiantes.removeAll();

    if (resultados.isEmpty()) {
        JLabel mensaje = new JLabel("No hay resultados encontrados", SwingConstants.CENTER);
        mensaje.setForeground(Color.GRAY);
        mensaje.setFont(new Font("Arial", Font.ITALIC, 16));
        mensaje.setAlignmentX(CENTER_ALIGNMENT);
        listaEstudiantes.add(Box.createVerticalGlue());
        listaEstudiantes.add(mensaje);
        listaEstudiantes.add(Box.createVerticalGlue());
    } else {
        for (Estudiante e : resultados) {
            ItemBusqueda item = new ItemBusqueda(this, usuario, e, gestor);
            listaEstudiantes.add(item);
        }
    }

    listaEstudiantes.revalidate();
    listaEstudiantes.repaint();
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jBotonLimipiarBusqueda = new javax.swing.JButton();
        campoBusqueda = new javax.swing.JTextField();
        jBotonBuscar = new javax.swing.JButton();
        jSeleccionadorDeCarrera = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaEstudiantes = new javax.swing.JPanel();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jBotonLimipiarBusqueda.setBackground(new java.awt.Color(240, 233, 248));
        jBotonLimipiarBusqueda.setForeground(new java.awt.Color(153, 153, 153));
        jBotonLimipiarBusqueda.setText("X");
        jBotonLimipiarBusqueda.setBorderPainted(false);
        jBotonLimipiarBusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBotonLimipiarBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonLimipiarBusquedaActionPerformed(evt);
            }
        });

        campoBusqueda.setBackground(new java.awt.Color(250, 236, 252));
        campoBusqueda.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        campoBusqueda.setForeground(new java.awt.Color(153, 153, 153));
        campoBusqueda.setText("Busque por nombre");
        campoBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoBusquedaMouseClicked(evt);
            }
        });
        campoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBusquedaActionPerformed(evt);
            }
        });

        jBotonBuscar.setBackground(new java.awt.Color(49, 148, 252));
        jBotonBuscar.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jBotonBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jBotonBuscar.setText("Buscar");
        jBotonBuscar.setBorderPainted(false);
        jBotonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonBuscarActionPerformed(evt);
            }
        });

        jSeleccionadorDeCarrera.setBackground(new java.awt.Color(250, 236, 252));
        jSeleccionadorDeCarrera.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jSeleccionadorDeCarrera.setForeground(new java.awt.Color(153, 153, 153));
        jSeleccionadorDeCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione su carrera", "Biología", "Física", "Licenciatura en Matemáticas", "Matemáticas", "Química", "Ingeniería de Sistemas", "Ingeniería Eléctrica", "Ingeniería Electrónica", "Ingeniería Industrial", "Ingeniería Mecánica", "Ingeniería Biomédica", "Ingeniería en Ciencia de Datos", "Diseño Industrial", "Ingeniería Civil", "Ingeniería Química", "Ingeniería de Petróleos", "Geología", "Enfermería", "Fisioterapia", "Medicina", "Microbiología y Bioanálisis", "Nutrición y Dietética", "Derecho", "Economía", "Filosofía", "Historia y Archivística", "Licenciatura en Educación Básica Primaria", "Licenciatura en Literatura y Lengua Castellana", "Licenciatura en Lenguas Extranjeras con énfasis en Inglés", "Licenciatura en Música", "Trabajo Social", "Técnica Profesional en Ejecución de Proyectos Culturales y Creativos" }));
        jSeleccionadorDeCarrera.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jScrollPane1.setBorder(null);

        listaEstudiantes.setBackground(new java.awt.Color(255, 255, 255));
        listaEstudiantes.setMinimumSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout listaEstudiantesLayout = new javax.swing.GroupLayout(listaEstudiantes);
        listaEstudiantes.setLayout(listaEstudiantesLayout);
        listaEstudiantesLayout.setHorizontalGroup(
            listaEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 978, Short.MAX_VALUE)
        );
        listaEstudiantesLayout.setVerticalGroup(
            listaEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(listaEstudiantes);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(campoBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(jSeleccionadorDeCarrera, 0, 143, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(jBotonBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBotonLimipiarBusqueda)
                        .addGap(102, 102, 102))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeleccionadorDeCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jBotonBuscar)
                                .addComponent(jBotonLimipiarBusqueda)))))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBusquedaActionPerformed

    private void jBotonLimipiarBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonLimipiarBusquedaActionPerformed
        campoBusqueda.setText("Busque por nombre");
        campoBusqueda.setForeground(new Color(153, 153, 153));
        jSeleccionadorDeCarrera.setSelectedIndex(0);
    }//GEN-LAST:event_jBotonLimipiarBusquedaActionPerformed

    private void jBotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonBuscarActionPerformed
        ejecutarBusqueda();
    }//GEN-LAST:event_jBotonBuscarActionPerformed

    private void campoBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoBusquedaMouseClicked
        if(campoBusqueda.getText().trim().equalsIgnoreCase("Busque por nombre")){
        campoBusqueda.setText("");
        campoBusqueda.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_campoBusquedaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoBusqueda;
    private javax.swing.JButton jBotonBuscar;
    private javax.swing.JButton jBotonLimipiarBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jSeleccionadorDeCarrera;
    private javax.swing.JPanel listaEstudiantes;
    // End of variables declaration//GEN-END:variables
}

