package com.mycompany.feedgrow.vista;
import com.mycompany.feedgrow.controlador.CalificarControlador;
import com.mycompany.feedgrow.modelo.CriterioEvaluacion;
import com.mycompany.feedgrow.modelo.Estudiante;
import com.mycompany.feedgrow.persistencia.GestorDatos;
import java.util.Map;
import javax.swing.JOptionPane;


public class Calificar extends javax.swing.JPanel {
private Estudiante usuario;
private Estudiante evaluado;
private GestorDatos gestor;
private boolean calificacionEdicion;
   
    public Calificar(Estudiante usuario, GestorDatos gestor, Estudiante evaluado, boolean isEdicion) {
        initComponents();
        this.gestor = gestor;
        this.evaluado = evaluado;
        this.usuario = usuario;
        this.calificacionEdicion = isEdicion;
        initCustom();
        initDatos(calificacionEdicion);
    }
private void initDatos(boolean t){
    if(t){
        Map m = gestor.buscarCalificacionPorEvaluadorYEvaluado(usuario, evaluado).getCalificaciones();
        jResponsabilidad.setText("" + m.get(CriterioEvaluacion.RESPONSABILIDAD));
        jColaboracion.setText("" + m.get(CriterioEvaluacion.COLABORACION));
        jComunicacion.setText("" +m.get(CriterioEvaluacion.COMUNICACION));
        jParticipacion.setText("" + m.get(CriterioEvaluacion.PARTICIPACION));
        jCompromiso.setText("" + m.get(CriterioEvaluacion.COMPROMISO));
        jIniciativa.setText("" + m.get(CriterioEvaluacion.INICIATIVA));
        jLiderazgo.setText("" + m.get(CriterioEvaluacion.LIDERAZGO));
        JResolucion.setText("" + m.get(CriterioEvaluacion.RESOLUCION_CONFLICTOS));
        jConfiabilidad.setText("" + m.get(CriterioEvaluacion.CONFIABILIDAD));
        jActitud.setText("" + m.get(CriterioEvaluacion.ACTITUD));
    }
}
private void initCustom(){
    Nombre.setText(evaluado.getNombre());
}

private void guardar(){
    CalificarControlador controller = new CalificarControlador(gestor);
    if (usuario == null || gestor == null) {
        JOptionPane.showMessageDialog(this, "No se pudo obtener el usuario actual o el gestor de datos.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    Map<CriterioEvaluacion, String> valoresTexto = Map.of(
    CriterioEvaluacion.RESPONSABILIDAD, jResponsabilidad.getText(),
    CriterioEvaluacion.COLABORACION, jColaboracion.getText(),
    CriterioEvaluacion.COMUNICACION, jComunicacion.getText(),
    CriterioEvaluacion.PARTICIPACION, jParticipacion.getText(),
    CriterioEvaluacion.COMPROMISO, jCompromiso.getText(),
    CriterioEvaluacion.INICIATIVA, jIniciativa.getText(),
    CriterioEvaluacion.LIDERAZGO, jLiderazgo.getText(),
    CriterioEvaluacion.RESOLUCION_CONFLICTOS, JResolucion.getText(),
    CriterioEvaluacion.CONFIABILIDAD, jConfiabilidad.getText(),
    CriterioEvaluacion.ACTITUD, jActitud.getText()
);

    String recomendacion = jRecomendacion.getText();
    String titulo = jTituloRecomendacion.getText();

    String mensaje = controller.agregarCalificacion(
        usuario,
        evaluado,
        valoresTexto,
        titulo,
        recomendacion, calificacionEdicion
);
if (mensaje.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Calificación guardada con éxito");
} else {
    JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.WARNING_MESSAGE);
}
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        fondo = new javax.swing.JPanel();
        Nombre = new javax.swing.JLabel();
        descripcionResponsabilidad = new javax.swing.JLabel();
        descripcionColaboracion = new javax.swing.JLabel();
        descripcionParticipacion = new javax.swing.JLabel();
        Comunicacion = new javax.swing.JLabel();
        descripcionComunicacion = new javax.swing.JLabel();
        Participacion = new javax.swing.JLabel();
        descripcionCompromiso = new javax.swing.JLabel();
        Responsabilidad = new javax.swing.JLabel();
        Colaboracion = new javax.swing.JLabel();
        jTituloRecomendacion = new javax.swing.JTextField();
        jActitud = new javax.swing.JTextField();
        jColaboracion = new javax.swing.JTextField();
        jComunicacion = new javax.swing.JTextField();
        jParticipacion = new javax.swing.JTextField();
        iniciativa = new javax.swing.JLabel();
        actitud = new javax.swing.JLabel();
        descripcionInciativa = new javax.swing.JLabel();
        descripcionActitud = new javax.swing.JLabel();
        liderazgo = new javax.swing.JLabel();
        descripcionLiderazgo = new javax.swing.JLabel();
        resolucionConflictos = new javax.swing.JLabel();
        descripcionResolucion = new javax.swing.JLabel();
        confiabilidad = new javax.swing.JLabel();
        descripcionConfiabilidad = new javax.swing.JLabel();
        jResponsabilidad = new javax.swing.JTextField();
        jIniciativa = new javax.swing.JTextField();
        jLiderazgo = new javax.swing.JTextField();
        JResolucion = new javax.swing.JTextField();
        jConfiabilidad = new javax.swing.JTextField();
        compromiso = new javax.swing.JLabel();
        jCompromiso = new javax.swing.JTextField();
        Recomendaciones = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        jRecomendacion = new javax.swing.JTextField();

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        fondo.setBackground(new java.awt.Color(255, 255, 255));

        Nombre.setFont(new java.awt.Font("Roboto", 0, 28)); // NOI18N
        Nombre.setForeground(new java.awt.Color(30, 30, 30));
        Nombre.setText("{estudiante nombre}");

        descripcionResponsabilidad.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        descripcionResponsabilidad.setForeground(new java.awt.Color(63, 69, 79));
        descripcionResponsabilidad.setText("Cumple las tareas a tiempo y con calidad.");

        descripcionColaboracion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        descripcionColaboracion.setForeground(new java.awt.Color(63, 69, 79));
        descripcionColaboracion.setText("Ayuda y aporta al trabajo conjunto.");

        descripcionParticipacion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        descripcionParticipacion.setForeground(new java.awt.Color(63, 69, 79));
        descripcionParticipacion.setText("Nivel de involucramiento en reuniones y discusiones.");

        Comunicacion.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        Comunicacion.setForeground(new java.awt.Color(30, 30, 30));
        Comunicacion.setText("Comunicación");

        descripcionComunicacion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        descripcionComunicacion.setForeground(new java.awt.Color(63, 69, 79));
        descripcionComunicacion.setText("Explica claro, escucha y respeta turnos.");

        Participacion.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        Participacion.setForeground(new java.awt.Color(30, 30, 30));
        Participacion.setText("Participación");

        descripcionCompromiso.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        descripcionCompromiso.setForeground(new java.awt.Color(63, 69, 79));
        descripcionCompromiso.setText("Demuestra interés y constancia en el proyecto.");

        Responsabilidad.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        Responsabilidad.setForeground(new java.awt.Color(30, 30, 30));
        Responsabilidad.setText("Responsabilidad");

        Colaboracion.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        Colaboracion.setForeground(new java.awt.Color(30, 30, 30));
        Colaboracion.setText("Colaboración");

        jTituloRecomendacion.setBackground(new java.awt.Color(200, 200, 200));
        jTituloRecomendacion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTituloRecomendacion.setForeground(new java.awt.Color(30, 30, 30));
        jTituloRecomendacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTituloRecomendacionActionPerformed(evt);
            }
        });

        jActitud.setBackground(new java.awt.Color(217, 217, 217));
        jActitud.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jActitud.setForeground(new java.awt.Color(30, 30, 30));

        jColaboracion.setBackground(new java.awt.Color(217, 217, 217));
        jColaboracion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jColaboracion.setForeground(new java.awt.Color(30, 30, 30));

        jComunicacion.setBackground(new java.awt.Color(217, 217, 217));
        jComunicacion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jComunicacion.setForeground(new java.awt.Color(30, 30, 30));

        jParticipacion.setBackground(new java.awt.Color(217, 217, 217));
        jParticipacion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jParticipacion.setForeground(new java.awt.Color(30, 30, 30));

        iniciativa.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        iniciativa.setForeground(new java.awt.Color(30, 30, 30));
        iniciativa.setText("Iniciativa");

        actitud.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        actitud.setForeground(new java.awt.Color(30, 30, 30));
        actitud.setText("Actitud");

        descripcionInciativa.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        descripcionInciativa.setForeground(new java.awt.Color(63, 69, 79));
        descripcionInciativa.setText("Propone ideas nuevas.");

        descripcionActitud.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        descripcionActitud.setForeground(new java.awt.Color(63, 69, 79));
        descripcionActitud.setText("Muestra disposición positiva, respeto y motivación.");

        liderazgo.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        liderazgo.setForeground(new java.awt.Color(30, 30, 30));
        liderazgo.setText("Liderazgo");

        descripcionLiderazgo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        descripcionLiderazgo.setForeground(new java.awt.Color(63, 69, 79));
        descripcionLiderazgo.setText("Motiva, organiza o guía al grupo cuando es necesario.");

        resolucionConflictos.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        resolucionConflictos.setForeground(new java.awt.Color(30, 30, 30));
        resolucionConflictos.setText("Resolución de conflictos");

        descripcionResolucion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        descripcionResolucion.setForeground(new java.awt.Color(63, 69, 79));
        descripcionResolucion.setText("Maneja diferencias sin generar discusiones negativas.");

        confiabilidad.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        confiabilidad.setForeground(new java.awt.Color(30, 30, 30));
        confiabilidad.setText("Confiabilidad");

        descripcionConfiabilidad.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        descripcionConfiabilidad.setForeground(new java.awt.Color(63, 69, 79));
        descripcionConfiabilidad.setText("El equipo puede contar con el/ella; cumple lo que promete.");

        jResponsabilidad.setBackground(new java.awt.Color(217, 217, 217));
        jResponsabilidad.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jResponsabilidad.setForeground(new java.awt.Color(30, 30, 30));

        jIniciativa.setBackground(new java.awt.Color(217, 217, 217));
        jIniciativa.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jIniciativa.setForeground(new java.awt.Color(30, 30, 30));
        jIniciativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIniciativaActionPerformed(evt);
            }
        });

        jLiderazgo.setBackground(new java.awt.Color(217, 217, 217));
        jLiderazgo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLiderazgo.setForeground(new java.awt.Color(30, 30, 30));

        JResolucion.setBackground(new java.awt.Color(217, 217, 217));
        JResolucion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        JResolucion.setForeground(new java.awt.Color(30, 30, 30));

        jConfiabilidad.setBackground(new java.awt.Color(217, 217, 217));
        jConfiabilidad.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jConfiabilidad.setForeground(new java.awt.Color(30, 30, 30));

        compromiso.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        compromiso.setForeground(new java.awt.Color(30, 30, 30));
        compromiso.setText("Compromiso");

        jCompromiso.setBackground(new java.awt.Color(217, 217, 217));
        jCompromiso.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jCompromiso.setForeground(new java.awt.Color(30, 30, 30));

        Recomendaciones.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        Recomendaciones.setForeground(new java.awt.Color(30, 30, 30));
        Recomendaciones.setText("Recomendaciones:");

        Guardar.setBackground(new java.awt.Color(0, 204, 102));
        Guardar.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Guardar.setText("Guardar cambios");
        Guardar.setBorderPainted(false);
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        jRecomendacion.setBackground(new java.awt.Color(200, 200, 200));
        jRecomendacion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jRecomendacion.setForeground(new java.awt.Color(30, 30, 30));
        jRecomendacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRecomendacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(240, 240, 240))
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(descripcionResponsabilidad, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                        .addGap(122, 122, 122))
                    .addComponent(Responsabilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jResponsabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(descripcionInciativa, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addGap(269, 269, 269))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                        .addComponent(iniciativa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLiderazgo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jIniciativa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jConfiabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jActitud, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))))
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(descripcionColaboracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(158, 158, 158))
                    .addComponent(Colaboracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jColaboracion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(liderazgo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(91, 91, 91))
                    .addComponent(descripcionLiderazgo))
                .addGap(107, 107, 107))
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(descripcionComunicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(134, 134, 134))
                    .addComponent(Comunicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jComunicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(resolucionConflictos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17))
                    .addComponent(descripcionResolucion))
                .addGap(103, 103, 103))
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(descripcionParticipacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(69, 69, 69))
                    .addComponent(Participacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jParticipacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(confiabilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(39, 39, 39))
                    .addComponent(descripcionConfiabilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(81, 81, 81))
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(descripcionCompromiso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(99, 99, 99))
                    .addComponent(compromiso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCompromiso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actitud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(descripcionActitud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(120, 120, 120))
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(Recomendaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(650, 650, 650))
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRecomendacion, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTituloRecomendacion, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(173, 173, 173)
                .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(Responsabilidad)
                        .addGap(3, 3, 3)
                        .addComponent(descripcionResponsabilidad))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jResponsabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iniciativa)
                            .addComponent(jIniciativa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addComponent(descripcionInciativa)))
                .addGap(5, 5, 5)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Colaboracion)
                        .addGap(3, 3, 3)
                        .addComponent(descripcionColaboracion))
                    .addComponent(jColaboracion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(liderazgo)
                            .addComponent(jLiderazgo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addComponent(descripcionLiderazgo)))
                .addGap(5, 5, 5)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Comunicacion)
                        .addGap(3, 3, 3)
                        .addComponent(descripcionComunicacion))
                    .addComponent(jComunicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(resolucionConflictos)
                            .addComponent(JResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addComponent(descripcionResolucion)))
                .addGap(5, 5, 5)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(confiabilidad)
                            .addComponent(jConfiabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addComponent(descripcionConfiabilidad))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(Participacion)
                                .addGap(3, 3, 3)
                                .addComponent(descripcionParticipacion))
                            .addComponent(jParticipacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(5, 5, 5)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(compromiso)
                        .addGap(3, 3, 3)
                        .addComponent(descripcionCompromiso))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jCompromiso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(actitud)
                            .addComponent(jActitud, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addComponent(descripcionActitud)))
                .addGap(35, 35, 35)
                .addComponent(Recomendaciones)
                .addGap(3, 3, 3)
                .addComponent(jTituloRecomendacion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRecomendacion, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Guardar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTituloRecomendacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTituloRecomendacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTituloRecomendacionActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        guardar();
    }//GEN-LAST:event_GuardarActionPerformed

    private void jRecomendacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRecomendacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRecomendacionActionPerformed

    private void jIniciativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIniciativaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIniciativaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Colaboracion;
    private javax.swing.JLabel Comunicacion;
    private javax.swing.JButton Guardar;
    private javax.swing.JTextField JResolucion;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Participacion;
    private javax.swing.JLabel Recomendaciones;
    private javax.swing.JLabel Responsabilidad;
    private javax.swing.JLabel actitud;
    private javax.swing.JLabel compromiso;
    private javax.swing.JLabel confiabilidad;
    private javax.swing.JLabel descripcionActitud;
    private javax.swing.JLabel descripcionColaboracion;
    private javax.swing.JLabel descripcionCompromiso;
    private javax.swing.JLabel descripcionComunicacion;
    private javax.swing.JLabel descripcionConfiabilidad;
    private javax.swing.JLabel descripcionInciativa;
    private javax.swing.JLabel descripcionLiderazgo;
    private javax.swing.JLabel descripcionParticipacion;
    private javax.swing.JLabel descripcionResolucion;
    private javax.swing.JLabel descripcionResponsabilidad;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel iniciativa;
    private javax.swing.JTextField jActitud;
    private javax.swing.JTextField jColaboracion;
    private javax.swing.JTextField jCompromiso;
    private javax.swing.JTextField jComunicacion;
    private javax.swing.JTextField jConfiabilidad;
    private javax.swing.JTextField jIniciativa;
    private javax.swing.JTextField jLiderazgo;
    private javax.swing.JTextField jParticipacion;
    private javax.swing.JTextField jRecomendacion;
    private javax.swing.JTextField jResponsabilidad;
    private javax.swing.JTextField jTituloRecomendacion;
    private javax.swing.JLabel liderazgo;
    private java.awt.Panel panel1;
    private javax.swing.JLabel resolucionConflictos;
    // End of variables declaration//GEN-END:variables
}
