
package com.mycompany.feedgrow.vista;


import com.mycompany.feedgrow.controlador.BusquedaControlador;
import com.mycompany.feedgrow.modelo.Estudiante;
import com.mycompany.feedgrow.persistencia.GestorDatos;
import java.awt.Color;
import static java.awt.Component.CENTER_ALIGNMENT;
import java.awt.Dimension;
import java.awt.Font;
import java.util.List;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

public class GestorMisCalificaciones extends javax.swing.JPanel {
private Estudiante usuario;
private GestorDatos gestor;

   
    public GestorMisCalificaciones(Estudiante usuario, GestorDatos gestor) {
        this.gestor = gestor;
        this.usuario = usuario;
        initComponents();
        initCustom();
        initLista();
    }
 private void initCustom() {
       
        contendorClaificaciones.setLayout(
            new javax.swing.BoxLayout(contendorClaificaciones, javax.swing.BoxLayout.Y_AXIS)
        );

        campoBusqueda.addActionListener(e -> ejecutarBusqueda());
    }
private void initLista(){
      BusquedaControlador controlador = new BusquedaControlador();
      List<Estudiante> resultados = controlador.buscar("", "", usuario, gestor.buscarEstudiantesCalificadosPorEvaluador(usuario));
      contendorClaificaciones.removeAll();
       for (Estudiante e : resultados) {
                ItemGestor item = new ItemGestor(usuario, gestor, e);
                contendorClaificaciones.add(item);
            }
       contendorClaificaciones.revalidate();
       contendorClaificaciones.repaint();
    }
  private void ejecutarBusqueda() {
  BusquedaControlador controlador = new BusquedaControlador();
    String nombre = campoBusqueda.getText().trim();
    String carrera = (String) jSeleccionadorDeCarrera.getSelectedItem();
    contendorClaificaciones.removeAll();
    contendorClaificaciones.setLayout(new BoxLayout(contendorClaificaciones, BoxLayout.Y_AXIS));
    contendorClaificaciones.setAlignmentX(LEFT_ALIGNMENT);
    List<Estudiante> resultados =
            controlador.buscar(nombre, carrera, usuario,
                               gestor.buscarEstudiantesCalificadosPorEvaluador(usuario));
    if (resultados.isEmpty()) {
        JLabel mensaje = new JLabel("No hay resultados encontrados", SwingConstants.CENTER);
        mensaje.setForeground(Color.GRAY);
        mensaje.setFont(new Font("Arial", Font.ITALIC, 16));
        mensaje.setAlignmentX(CENTER_ALIGNMENT);
        contendorClaificaciones.add(Box.createVerticalGlue());
        contendorClaificaciones.add(mensaje);
        contendorClaificaciones.add(Box.createVerticalGlue());
    } else {
        for (Estudiante e : resultados) {

            ItemGestor item = new ItemGestor(usuario, gestor, e);
            item.setAlignmentX(LEFT_ALIGNMENT);
            item.setMaximumSize(
                new Dimension(Integer.MAX_VALUE, item.getPreferredSize().height)
            );

            contendorClaificaciones.add(item);
        }
    }

    contendorClaificaciones.revalidate();
    contendorClaificaciones.repaint();
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBuscar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListResultados = new javax.swing.JList<>();
        fondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoBusqueda = new javax.swing.JTextField();
        jSeleccionadorDeCarrera = new javax.swing.JComboBox<>();
        jBotonBuscar = new javax.swing.JButton();
        jBotonLimipiarBusqueda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        contendorClaificaciones = new javax.swing.JPanel();

        txtBuscar.setBackground(new java.awt.Color(240, 233, 255));
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        jListResultados.setToolTipText("");
        jListResultados.setAutoscrolls(false);
        jListResultados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(jListResultados);

        fondo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto SemiBold", 0, 45)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 30, 30));
        jLabel1.setText("Mis Calificaciones");

        campoBusqueda.setBackground(new java.awt.Color(250, 236, 252));
        campoBusqueda.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        campoBusqueda.setForeground(new java.awt.Color(153, 153, 153));
        campoBusqueda.setText("Busque por nombre");
        campoBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoBusquedaMouseClicked(evt);
            }
        });
        campoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBusquedaActionPerformed(evt);
            }
        });

        jSeleccionadorDeCarrera.setBackground(new java.awt.Color(250, 236, 252));
        jSeleccionadorDeCarrera.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jSeleccionadorDeCarrera.setForeground(new java.awt.Color(153, 153, 153));
        jSeleccionadorDeCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione su carrera", "Biología", "Física", "Licenciatura en Matemáticas", "Matemáticas", "Química", "Ingeniería de Sistemas", "Ingeniería Eléctrica", "Ingeniería Electrónica", "Ingeniería Industrial", "Ingeniería Mecánica", "Ingeniería Biomédica", "Ingeniería en Ciencia de Datos", "Diseño Industrial", "Ingeniería Civil", "Ingeniería Química", "Ingeniería de Petróleos", "Geología", "Enfermería", "Fisioterapia", "Medicina", "Microbiología y Bioanálisis", "Nutrición y Dietética", "Derecho", "Economía", "Filosofía", "Historia y Archivística", "Licenciatura en Educación Básica Primaria", "Licenciatura en Literatura y Lengua Castellana", "Licenciatura en Lenguas Extranjeras con énfasis en Inglés", "Licenciatura en Música", "Trabajo Social", "Técnica Profesional en Ejecución de Proyectos Culturales y Creativos" }));
        jSeleccionadorDeCarrera.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jBotonBuscar.setBackground(new java.awt.Color(49, 148, 252));
        jBotonBuscar.setText("Buscar");
        jBotonBuscar.setBorderPainted(false);
        jBotonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonBuscarActionPerformed(evt);
            }
        });

        jBotonLimipiarBusqueda.setBackground(new java.awt.Color(240, 233, 248));
        jBotonLimipiarBusqueda.setText("X");
        jBotonLimipiarBusqueda.setBorderPainted(false);
        jBotonLimipiarBusqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBotonLimipiarBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonLimipiarBusquedaActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(null);

        contendorClaificaciones.setBackground(new java.awt.Color(255, 255, 255));
        contendorClaificaciones.setMinimumSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout contendorClaificacionesLayout = new javax.swing.GroupLayout(contendorClaificaciones);
        contendorClaificaciones.setLayout(contendorClaificacionesLayout);
        contendorClaificacionesLayout.setHorizontalGroup(
            contendorClaificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 964, Short.MAX_VALUE)
        );
        contendorClaificacionesLayout.setVerticalGroup(
            contendorClaificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(contendorClaificaciones);

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(campoBusqueda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeleccionadorDeCarrera, 0, 1, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBotonBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBotonLimipiarBusqueda)
                .addGap(88, 88, 88))
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 892, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSeleccionadorDeCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBotonBuscar)
                        .addComponent(jBotonLimipiarBusqueda)))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void campoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBusquedaActionPerformed

    private void jBotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonBuscarActionPerformed
        ejecutarBusqueda();
    }//GEN-LAST:event_jBotonBuscarActionPerformed

    private void jBotonLimipiarBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonLimipiarBusquedaActionPerformed
        campoBusqueda.setText("Busque por nombre");
        campoBusqueda.setForeground(new Color(153, 153, 153));
        jSeleccionadorDeCarrera.setSelectedIndex(0);
    }//GEN-LAST:event_jBotonLimipiarBusquedaActionPerformed

    private void campoBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoBusquedaMouseClicked
    if(campoBusqueda.getText().trim().equalsIgnoreCase("Busque por nombre")){
        campoBusqueda.setText("");
        campoBusqueda.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_campoBusquedaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoBusqueda;
    private javax.swing.JPanel contendorClaificaciones;
    private javax.swing.JPanel fondo;
    private javax.swing.JButton jBotonBuscar;
    private javax.swing.JButton jBotonLimipiarBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<Estudiante> jListResultados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jSeleccionadorDeCarrera;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
