
package com.mycompany.feedgrow.vista;

import com.mycompany.feedgrow.controlador.InicioDeSesionControlador;
import com.mycompany.feedgrow.modelo.Estudiante;
import com.mycompany.feedgrow.persistencia.GestorDatos;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JPanel;

public class InicioDeSesion extends javax.swing.JFrame {
private final GestorDatos gestor;

    public InicioDeSesion(GestorDatos gestor) {
        this.gestor = gestor;
        initComponents();
        initLocation();
        initCustom();

    }
    
 private void initCustom() {
    agregarDegradado(jPanel1, new Degradado(19, 188, 129, 22, 140, 202, false));   
}
 private void initLocation(){
    Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
    int x = (pantalla.width - this.getWidth()) / 2;
    int y = (pantalla.height - this.getHeight()) / 2;
    this.setLocation(x, y);
}

private void agregarDegradado(JPanel destino, Degradado fondo) {
    fondo.setBounds(0, 0, destino.getWidth(), destino.getHeight());
    destino.add(fondo);
    destino.setComponentZOrder(fondo, destino.getComponentCount() - 1); // asegurarse de que el fondo quede atrás

    destino.addComponentListener(new java.awt.event.ComponentAdapter() {
        @Override
        public void componentResized(java.awt.event.ComponentEvent e) {
            fondo.setSize(destino.getSize());
        }
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JTextField();
        IndicadorUsuario = new javax.swing.JLabel();
        botonAceptar = new javax.swing.JButton();
        registrarse = new javax.swing.JLabel();
        título = new javax.swing.JLabel();
        campoContraseña = new javax.swing.JPasswordField();
        indicadorContraseña = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(230, 246, 246));

        jPanel3.setBackground(new java.awt.Color(230, 246, 246));
        jPanel3.setForeground(new java.awt.Color(225, 225, 225));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.setPreferredSize(new java.awt.Dimension(550, 451));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedGrow_241x86.png.png"))); // NOI18N
        logo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        campoUsuario.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        campoUsuario.setForeground(new java.awt.Color(153, 153, 153));
        campoUsuario.setText("Ingrese su usuario");
        campoUsuario.setBorder(null);
        campoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoUsuarioMouseClicked(evt);
            }
        });

        IndicadorUsuario.setBackground(new java.awt.Color(102, 102, 102));
        IndicadorUsuario.setFont(new java.awt.Font("Roboto SemiBold", 0, 14)); // NOI18N
        IndicadorUsuario.setForeground(new java.awt.Color(102, 102, 102));
        IndicadorUsuario.setText("Código");

        botonAceptar.setBackground(new java.awt.Color(49, 148, 252));
        botonAceptar.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        botonAceptar.setForeground(new java.awt.Color(255, 255, 255));
        botonAceptar.setText("Aceptar");
        botonAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAceptarMouseClicked(evt);
            }
        });
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        registrarse.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        registrarse.setForeground(new java.awt.Color(102, 102, 102));
        registrarse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrarse.setText("O registrarse");
        registrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        registrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrarseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registrarseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registrarseMouseExited(evt);
            }
        });

        título.setFont(new java.awt.Font("Roboto SemiBold", 1, 18)); // NOI18N
        título.setForeground(new java.awt.Color(102, 102, 102));
        título.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        título.setText("INICIAR SESIÓN");

        campoContraseña.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        campoContraseña.setForeground(new java.awt.Color(153, 153, 153));
        campoContraseña.setText("wwwwwww");
        campoContraseña.setBorder(null);
        campoContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoContraseñaMouseClicked(evt);
            }
        });

        indicadorContraseña.setFont(new java.awt.Font("Roboto SemiBold", 0, 14)); // NOI18N
        indicadorContraseña.setForeground(new java.awt.Color(102, 102, 102));
        indicadorContraseña.setText("Contraseña");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(campoUsuario)
                            .addComponent(campoContraseña)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(indicadorContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(119, 119, 119))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(registrarse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(102, 102, 102))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(botonAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(94, 94, 94)))
                .addGap(63, 63, 63))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(título, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(54, 54, 54))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(IndicadorUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(234, 234, 234))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(logo)
                .addGap(30, 30, 30)
                .addComponent(título)
                .addGap(24, 24, 24)
                .addComponent(IndicadorUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(indicadorContraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(botonAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registrarse)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleParent(registrarse);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void campoUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoUsuarioMouseClicked
        campoUsuario.setText("");
        campoUsuario.setForeground(Color.black);
     }//        campoUsuario.setForeground(Color.blacampoCódigo        campoUsuario.setForeground(Color.blacampoCódigo                      campoUsuario//GEN-LAST:event_campoUsuarioMouseClicked

    private void campoContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoContraseñaMouseClicked
        campoContraseña.setText("");
        campoContraseña.setForeground(Color.black);
    }//GEN-LAST:event_campoContraseñaMouseClicked

    private void botonAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAceptarMouseClicked
    InicioDeSesionControlador controlador = new InicioDeSesionControlador(this.gestor);
    String codigoIngresado = campoUsuario.getText().trim();
    String contraseñaIngresada = String.valueOf(campoContraseña.getPassword());
    
    String errorCampos = controlador.validarCamposLogin(codigoIngresado, contraseñaIngresada);
    if (!errorCampos.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, errorCampos, "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    String errorLogin = controlador.verificarUsuario(codigoIngresado, contraseñaIngresada);
    if (!errorLogin.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, errorLogin, "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }
    Estudiante e = gestor.buscarEstudiantePorCodigo(codigoIngresado);
    javax.swing.JOptionPane.showMessageDialog(this,
            "Inicio de sesión exitoso. Bienvenido/a " + e.getNombre() + "!",
            "Éxito",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);

     PáginaMenú ventana = new PáginaMenú(gestor, e);
     ventana.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_botonAceptarMouseClicked

    private void registrarseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarseMouseEntered
        registrarse.setForeground(new Color(22, 122, 135));
    }//GEN-LAST:event_registrarseMouseEntered

    private void registrarseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarseMouseExited
       registrarse.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_registrarseMouseExited

    private void registrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarseMouseClicked
        Registro ventana = new Registro(gestor);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registrarseMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IndicadorUsuario;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JPasswordField campoContraseña;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JLabel indicadorContraseña;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel registrarse;
    private javax.swing.JLabel título;
    // End of variables declaration//GEN-END:variables
}
