
package com.mycompany.feedgrow.vista;

import com.mycompany.feedgrow.controlador.CalificarControlador;
import com.mycompany.feedgrow.modelo.Calificacion;
import com.mycompany.feedgrow.modelo.Estudiante;
import com.mycompany.feedgrow.persistencia.GestorDatos;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;


public class ItemGestor extends javax.swing.JPanel {
    private Calificacion calificacion;
    private GestorDatos gestor;
    private Estudiante evaluado;
    private Estudiante usuario;

    public ItemGestor(Estudiante usuario, GestorDatos gestor, Estudiante estudiante) {
        initComponents();
        this.evaluado = estudiante;
        this.calificacion = gestor.buscarCalificacionPorEvaluadorYEvaluado(usuario, estudiante);
        this.gestor = gestor;
        this.usuario = usuario;
        cargarDatos();
    }

    private void cargarDatos() {
        nombre.setText(evaluado.getNombre());
        jcarrera.setText("Carrera • " + evaluado.getCarrera());
        jAtributo.setText(evaluado.getPerfil().getMejoresAtributos());
       
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        inconoUsuario = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        jcarrera = new javax.swing.JLabel();
        botonEliminar = new javax.swing.JButton();
        botonEditar = new javax.swing.JButton();
        jAtributo = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setMinimumSize(new java.awt.Dimension(900, 99));

        inconoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        inconoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Captura de pantalla 2025-11-16 151859.png"))); // NOI18N

        nombre.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        nombre.setForeground(new java.awt.Color(30, 30, 30));
        nombre.setText("{estudiante nombre}");

        jcarrera.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jcarrera.setForeground(new java.awt.Color(63, 69, 79));
        jcarrera.setText("Carrera • {estudiante carrera}");

        botonEliminar.setBackground(new java.awt.Color(230, 37, 37));
        botonEliminar.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        botonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        botonEliminar.setText("Eliminar");
        botonEliminar.setBorderPainted(false);
        botonEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        botonEditar.setBackground(new java.awt.Color(54, 197, 68));
        botonEditar.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        botonEditar.setForeground(new java.awt.Color(255, 255, 255));
        botonEditar.setText("Editar");
        botonEditar.setBorderPainted(false);
        botonEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });

        jAtributo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jAtributo.setForeground(new java.awt.Color(63, 69, 79));
        jAtributo.setText("{calificacion atributo}");

        separador.setForeground(new java.awt.Color(202, 196, 208));

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(inconoUsuario)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jAtributo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(jcarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(20, 20, 20))))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(inconoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(botonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(fondoLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jcarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
          if (calificacion == null) return;
          CalificarControlador controlador = new CalificarControlador(gestor);
          String error = controlador.eliminarCalificacion(usuario, evaluado, calificacion);
          if(!error.isBlank()){
              JOptionPane.showMessageDialog(this, error, "Error al eliminar", JOptionPane.ERROR_MESSAGE);
              return;
          }
    java.awt.Window w = SwingUtilities.getWindowAncestor(this);
    if (w instanceof PáginaMenú) {
        PáginaMenú frame = (PáginaMenú) w;
        GestorMisCalificaciones nuevoPanel = new GestorMisCalificaciones(usuario, gestor);
        frame.cambiarPanel(nuevoPanel);
    }
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        if (calificacion == null) return;
        java.awt.Window w = SwingUtilities.getWindowAncestor(this);
    if (w instanceof PáginaMenú) {
        PáginaMenú frame = (PáginaMenú) w;
        Calificar nuevoPanel = new Calificar(usuario, gestor, evaluado, true);
        frame.cambiarPanel(nuevoPanel);
    }
    }//GEN-LAST:event_botonEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel inconoUsuario;
    private javax.swing.JLabel jAtributo;
    private javax.swing.JLabel jcarrera;
    private javax.swing.JLabel nombre;
    private javax.swing.JSeparator separador;
    // End of variables declaration//GEN-END:variables
}
