
package com.mycompany.feedgrow.vista;
import com.mycompany.feedgrow.modelo.Estudiante;
import com.mycompany.feedgrow.persistencia.GestorDatos;
import java.awt.Color;
import java.awt.Cursor;
import java.util.Locale;
import javax.swing.SwingUtilities;

public class ItemBusqueda extends javax.swing.JPanel {
    private Estudiante estudiante;
    private Busqueda busqueda;
    private GestorDatos gestor;
    private Estudiante usuario;

    public ItemBusqueda(Busqueda busqueda, Estudiante usuario, Estudiante estudiante, GestorDatos gestor) {
        this.estudiante = estudiante;
        this.gestor = gestor;
        this.busqueda = busqueda;
        this.usuario = usuario;
        initComponents(); 
        initCustom();     
    }

    private void initCustom() {
        cargarDatos();
        configurarNombreClicable();
    }

    private void cargarDatos() {
        if (estudiante == null) return;
        nombre.setText(estudiante.getNombre());
        String carrera = estudiante.getCarrera() != null ? estudiante.getCarrera() : "";
        jCarrera.setText("Carrera • " + carrera);
        double score = 0.0;
        String attrs = "";
        if (estudiante.getPerfil() != null) {
            try {
                attrs = estudiante.getPerfil().getMejoresAtributos();
                score = estudiante.getPerfil().getPromedioGlobal();
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        }
        jMejoresAtributos.setText(attrs);
        promedio.setText(String.format(Locale.forLanguageTag("es-CO"), "%.1f", score));
    }

    private void configurarNombreClicable() {
        nombre.setForeground(Color.BLACK);
        nombre.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirPerfil();
            }

            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nombre.setForeground(Color.BLUE);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nombre.setForeground(Color.BLACK);
            }
        });
    }

    private void abrirPerfil() {
        java.awt.Window w = SwingUtilities.getWindowAncestor(this);

        if (w instanceof PáginaMenú) {
            PáginaMenú frame = (PáginaMenú) w;
            PerfilOtro panel = new PerfilOtro(usuario, gestor, estudiante);
            frame.cambiarPanel(panel);
        }
    }



    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        iconoUsuario = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        jMejoresAtributos = new javax.swing.JLabel();
        promedio = new javax.swing.JLabel();
        jCarrera = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();

        fondo.setBackground(new java.awt.Color(255, 255, 255));

        iconoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Captura de pantalla 2025-11-16 151912.png"))); // NOI18N

        nombre.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        nombre.setForeground(new java.awt.Color(29, 27, 32));
        nombre.setText("{estudiante nombre}");

        jMejoresAtributos.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jMejoresAtributos.setForeground(new java.awt.Color(63, 69, 79));
        jMejoresAtributos.setText("{mejores atributos}");

        promedio.setFont(new java.awt.Font("Roboto", 0, 23)); // NOI18N
        promedio.setForeground(new java.awt.Color(30, 30, 30));
        promedio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Captura de pantalla 2025-11-11 220725.png"))); // NOI18N
        promedio.setText("0,0");

        jCarrera.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jCarrera.setForeground(new java.awt.Color(63, 69, 79));
        jCarrera.setText("Carrera • {estudiante carrera}");

        separador.setForeground(new java.awt.Color(202, 196, 208));

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(iconoUsuario)
                        .addGap(4, 4, 4)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jMejoresAtributos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(fondoLayout.createSequentialGroup()
                                        .addComponent(jCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(251, 251, 251)))
                                .addGap(130, 130, 130)))
                        .addGap(10, 10, 10)
                        .addComponent(promedio)
                        .addGap(62, 62, 62))
                    .addComponent(separador))
                .addGap(16, 16, 16))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jMejoresAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(promedio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel iconoUsuario;
    private javax.swing.JLabel jCarrera;
    private javax.swing.JLabel jMejoresAtributos;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel promedio;
    private javax.swing.JSeparator separador;
    // End of variables declaration//GEN-END:variables
}
