/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.feedgrow.vista;

import com.mycompany.feedgrow.modelo.Estudiante;
import java.util.Arrays;
import java.util.Locale;

/**
 *
 * @author micha
 */
public class ItemRanking extends javax.swing.JPanel {
private Estudiante estudiante;
    /**
     * Creates new form ItemRanking
     */
    public ItemRanking(Estudiante estudiante) {
        initComponents();
        this.estudiante = estudiante;
        initCustom();
    }
private void initCustom() {
        if (estudiante == null) return;

        
       nombre1.setText(estudiante.getNombre());
        carrera.setText("Carrera • " + estudiante.getCarrera());

        
        if (estudiante.getPerfil() != null) {
            var perfil = estudiante.getPerfil();

            
            double score = perfil.getPromedioGlobal();
            promedio.setText(String.format(Locale.US, "%.1f", score));

            
            String attrs = perfil.getMejoresAtributos();
            if (attrs != null && !attrs.isBlank()) {
             mejoresAtributos.setText(attrs);
            } else {
                mejoresAtributos.setText("");
            }
        } else {
            promedio.setText("—");
            mejoresAtributos.setText("");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        jMejoresAtributos = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCarrera = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        fondo = new javax.swing.JPanel();
        iconoMedalla = new javax.swing.JLabel();
        nombre1 = new javax.swing.JLabel();
        mejoresAtributos = new javax.swing.JLabel();
        promedio = new javax.swing.JLabel();
        carrera = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Captura de pantalla 2025-11-16 151912.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        nombre.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        nombre.setText("{estudiante nombre}");
        jPanel2.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, 36));

        jMejoresAtributos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMejoresAtributos.setText("{mejores atributos}");
        jPanel2.add(jMejoresAtributos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Captura de pantalla 2025-11-11 220725.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, 50));

        jCarrera.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCarrera.setText("Carrera • {estudiante carrera}");
        jPanel2.add(jCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, 30));

        fondo.setBackground(new java.awt.Color(255, 255, 255));

        iconoMedalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medalla96x96.png"))); // NOI18N

        nombre1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        nombre1.setForeground(new java.awt.Color(30, 30, 30));
        nombre1.setText("{estudiante nombre}");

        mejoresAtributos.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        mejoresAtributos.setForeground(new java.awt.Color(63, 69, 79));
        mejoresAtributos.setText("{mejores atributos}");

        promedio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        promedio.setForeground(new java.awt.Color(30, 30, 30));
        promedio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Captura de pantalla 2025-11-11 220725.png"))); // NOI18N
        promedio.setText("0,0");

        carrera.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        carrera.setForeground(new java.awt.Color(63, 69, 79));
        carrera.setText("Carrera • {estudiante carrera}");

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(iconoMedalla)
                .addGap(4, 4, 4)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(carrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(9, 9, 9)))
                        .addGap(152, 152, 152)
                        .addComponent(promedio))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(mejoresAtributos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(38, 38, 38)))
                .addGap(195, 195, 195))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconoMedalla)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(carrera, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(promedio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(mejoresAtributos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel carrera;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel iconoMedalla;
    private javax.swing.JLabel jCarrera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jMejoresAtributos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mejoresAtributos;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel nombre1;
    private javax.swing.JLabel promedio;
    // End of variables declaration//GEN-END:variables
}
