
package com.mycompany.feedgrow.vista;

import com.mycompany.feedgrow.modelo.Calificacion;
import com.mycompany.feedgrow.modelo.Estudiante;
import java.awt.Color;
import static java.awt.Component.CENTER_ALIGNMENT;
import static java.awt.Component.LEFT_ALIGNMENT;
import java.awt.Dimension;
import java.awt.Font;
import java.util.List;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;


public class Principal extends javax.swing.JPanel {
 private final Estudiante estudiante;
    
    public Principal(Estudiante e) {
        this.estudiante = e;
        initComponents();
        initCustom();
        initRecomendaciones();
    }
 private void initCustom() {
    agregarDegradado(panelDegradado, new Degradado(19, 188, 129, 22, 140, 202, true));
    textoSaludo.setText("Bienvenid@ " + estudiante.getNombre());
    textoSaludo.setForeground(Color.white);
    textoUltimasRecomendaciones.setForeground(Color.white);
}

private void agregarDegradado(JPanel destino, Degradado fondo) {
    fondo.setBounds(0, 0, destino.getWidth(), destino.getHeight());
    destino.add(fondo);
    destino.setComponentZOrder(fondo, destino.getComponentCount() - 1); // asegurarse de que el fondo quede atrás

    destino.addComponentListener(new java.awt.event.ComponentAdapter() {
        @Override
        public void componentResized(java.awt.event.ComponentEvent e) {
            fondo.setSize(destino.getSize());
        }
    });
}


    private void initRecomendaciones(){
        contenedorRecomendaciones.removeAll();
        contenedorRecomendaciones.setLayout(new BoxLayout(contenedorRecomendaciones, BoxLayout.Y_AXIS));
        contenedorRecomendaciones.setAlignmentX(LEFT_ALIGNMENT);
        List<Calificacion> resultados = estudiante.getCalificacionesRecibidas();
        if (resultados.isEmpty()) {
            JLabel mensaje = new JLabel("No hay resultados encontrados", SwingConstants.CENTER);
            mensaje.setForeground(Color.GRAY);
            mensaje.setFont(new Font("Arial", Font.ITALIC, 16));
            mensaje.setAlignmentX(CENTER_ALIGNMENT);
            contenedorRecomendaciones.add(Box.createVerticalGlue());
            contenedorRecomendaciones.add(mensaje);
            contenedorRecomendaciones.add(Box.createVerticalGlue());
        } else {
            for (Calificacion c : resultados) {

                ItemRecomendacion item = new ItemRecomendacion(c.getTituloRecomendacion(), c.getRecomendacion());
                item.setAlignmentX(LEFT_ALIGNMENT);
                item.setMaximumSize(
                    new Dimension(Integer.MAX_VALUE, item.getPreferredSize().height)
                );
                contenedorRecomendaciones.add(item);
            }
        }
        contenedorRecomendaciones.revalidate();
        contenedorRecomendaciones.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        panelDegradado = new javax.swing.JPanel();
        textoSaludo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        textoUltimasRecomendaciones = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        contenedorRecomendaciones = new javax.swing.JPanel();

        fondo.setBackground(new java.awt.Color(255, 255, 255));

        panelDegradado.setBackground(new java.awt.Color(25, 123, 144));

        textoSaludo.setBackground(new java.awt.Color(255, 255, 255));
        textoSaludo.setFont(new java.awt.Font("Roboto SemiBold", 0, 36)); // NOI18N
        textoSaludo.setText("Bienvenid@ {estudiante nombre}");

        javax.swing.GroupLayout panelDegradadoLayout = new javax.swing.GroupLayout(panelDegradado);
        panelDegradado.setLayout(panelDegradadoLayout);
        panelDegradadoLayout.setHorizontalGroup(
            panelDegradadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDegradadoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(textoSaludo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(232, 232, 232))
        );
        panelDegradadoLayout.setVerticalGroup(
            panelDegradadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDegradadoLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(textoSaludo)
                .addGap(23, 23, 23))
        );

        jPanel2.setBackground(new java.awt.Color(98, 91, 113));

        textoUltimasRecomendaciones.setBackground(new java.awt.Color(255, 255, 255));
        textoUltimasRecomendaciones.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        textoUltimasRecomendaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoUltimasRecomendaciones.setText("Últimas recomendaciones");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textoUltimasRecomendaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textoUltimasRecomendaciones)
                .addContainerGap())
        );

        scroll.setBorder(null);

        contenedorRecomendaciones.setBackground(new java.awt.Color(255, 255, 255));
        contenedorRecomendaciones.setToolTipText("");
        contenedorRecomendaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout contenedorRecomendacionesLayout = new javax.swing.GroupLayout(contenedorRecomendaciones);
        contenedorRecomendaciones.setLayout(contenedorRecomendacionesLayout);
        contenedorRecomendacionesLayout.setHorizontalGroup(
            contenedorRecomendacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        contenedorRecomendacionesLayout.setVerticalGroup(
            contenedorRecomendacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        scroll.setViewportView(contenedorRecomendaciones);

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(panelDegradado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(105, 105, 105))
            .addGroup(fondoLayout.createSequentialGroup()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(panelDegradado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedorRecomendaciones;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelDegradado;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JLabel textoSaludo;
    private javax.swing.JLabel textoUltimasRecomendaciones;
    // End of variables declaration//GEN-END:variables
}
