
package com.mycompany.feeedgrow.vista;

import com.mycompany.feeedgrow.controlador.BusquedaControlador;
import com.mycompany.feeedgrow.modelo.Estudiante;
import com.mycompany.feeedgrow.persistencia.GestorDatos;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

public class Busqueda extends JPanel {

    private final GestorDatos gestor;
    private final Estudiante usuario;

    public Busqueda( Estudiante usuario, GestorDatos gestor) {
        this.gestor = gestor;
        this.usuario = usuario;
        initComponents();
        initCustom();
    }

    private void initCustom() {
       
        listaEstudiantes.setLayout(
            new javax.swing.BoxLayout(listaEstudiantes, javax.swing.BoxLayout.Y_AXIS)
        );

        campoBusqueda.addActionListener(e -> ejecutarBusqueda());
    }


   private void ejecutarBusqueda() {
    BusquedaControlador controlador = new BusquedaControlador();
    String nombre = campoBusqueda.getText().trim();
    String carrera = (String) jSeleccionadorDeCarrera.getSelectedItem();

    List<Estudiante> resultados = controlador.buscar(nombre, carrera, usuario, gestor.getEstudiantes());
    listaEstudiantes.removeAll();

    if (resultados.isEmpty()) {
        JLabel mensaje = new JLabel("No hay resultados encontrados", SwingConstants.CENTER);
        mensaje.setForeground(Color.GRAY);
        mensaje.setFont(new Font("Arial", Font.ITALIC, 16));
        mensaje.setAlignmentX(CENTER_ALIGNMENT);
        listaEstudiantes.add(Box.createVerticalGlue());
        listaEstudiantes.add(mensaje);
        listaEstudiantes.add(Box.createVerticalGlue());
    } else {
        for (Estudiante e : resultados) {
            ItemBusqueda item = new ItemBusqueda(this, usuario, e, gestor);
            listaEstudiantes.add(item);
        }
    }

    listaEstudiantes.revalidate();
    listaEstudiantes.repaint();
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jBotonLimipiarBusqueda = new javax.swing.JButton();
        campoBusqueda = new javax.swing.JTextField();
        jBotonBuscar = new javax.swing.JButton();
        jSeleccionadorDeCarrera = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaEstudiantes = new javax.swing.JPanel();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBotonLimipiarBusqueda.setBackground(new java.awt.Color(240, 233, 248));
        jBotonLimipiarBusqueda.setForeground(new java.awt.Color(153, 153, 153));
        jBotonLimipiarBusqueda.setText("X");
        jBotonLimipiarBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonLimipiarBusquedaActionPerformed(evt);
            }
        });
        jPanel12.add(jBotonLimipiarBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 40, -1, -1));

        campoBusqueda.setBackground(new java.awt.Color(250, 236, 252));
        campoBusqueda.setForeground(new java.awt.Color(153, 153, 153));
        campoBusqueda.setText("Busque por nombre");
        campoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBusquedaActionPerformed(evt);
            }
        });
        jPanel12.add(campoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 520, 35));

        jBotonBuscar.setBackground(new java.awt.Color(49, 148, 252));
        jBotonBuscar.setText("Buscar");
        jBotonBuscar.setBorderPainted(false);
        jBotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonBuscarActionPerformed(evt);
            }
        });
        jPanel12.add(jBotonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 40, -1, -1));

        jSeleccionadorDeCarrera.setBackground(new java.awt.Color(250, 236, 252));
        jSeleccionadorDeCarrera.setForeground(new java.awt.Color(153, 153, 153));
        jSeleccionadorDeCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione su carrera", "Biología", "Física", "Licenciatura en Matemáticas", "Matemáticas", "Química", "Ingeniería de Sistemas", "Ingeniería Eléctrica", "Ingeniería Electrónica", "Ingeniería Industrial", "Ingeniería Mecánica", "Ingeniería Biomédica", "Ingeniería en Ciencia de Datos", "Diseño Industrial", "Ingeniería Civil", "Ingeniería Química", "Ingeniería de Petróleos", "Geología", "Enfermería", "Fisioterapia", "Medicina", "Microbiología y Bioanálisis", "Nutrición y Dietética", "Derecho", "Economía", "Filosofía", "Historia y Archivística", "Licenciatura en Educación Básica Primaria", "Licenciatura en Literatura y Lengua Castellana", "Licenciatura en Lenguas Extranjeras con énfasis en Inglés", "Licenciatura en Música", "Trabajo Social", "Técnica Profesional en Ejecución de Proyectos Culturales y Creativos" }));
        jSeleccionadorDeCarrera.setBorder(null);
        jPanel12.add(jSeleccionadorDeCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 140, -1));

        jScrollPane1.setBorder(null);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        listaEstudiantes.setBackground(new java.awt.Color(255, 255, 255));
        listaEstudiantes.setMinimumSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout listaEstudiantesLayout = new javax.swing.GroupLayout(listaEstudiantes);
        listaEstudiantes.setLayout(listaEstudiantesLayout);
        listaEstudiantesLayout.setHorizontalGroup(
            listaEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 978, Short.MAX_VALUE)
        );
        listaEstudiantesLayout.setVerticalGroup(
            listaEstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(listaEstudiantes);

        jPanel12.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 960, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 984, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBusquedaActionPerformed

    private void jBotonLimipiarBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonLimipiarBusquedaActionPerformed
        campoBusqueda.setText("");
    }//GEN-LAST:event_jBotonLimipiarBusquedaActionPerformed

    private void jBotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonBuscarActionPerformed
        ejecutarBusqueda();
    }//GEN-LAST:event_jBotonBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoBusqueda;
    private javax.swing.JButton jBotonBuscar;
    private javax.swing.JButton jBotonLimipiarBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jSeleccionadorDeCarrera;
    private javax.swing.JPanel listaEstudiantes;
    // End of variables declaration//GEN-END:variables
}

