/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.feeedgrow.vista;

import com.mycompany.feeedgrow.modelo.Estudiante;
import com.mycompany.feeedgrow.modelo.GestorDatos;
import javax.swing.JPanel;
import com.mycompany.feeedgrow.vista.DiseñoBusqueda;
import com.mycompany.feeedgrow.vista.PáginaMenú;
import com.mycompany.feeedgrow.vista.Perfil;

public class Busqueda extends JPanel {

    private GestorDatos gestor;

    public Busqueda(GestorDatos gestor) {
        this.gestor = gestor;
        initComponents();
        initCustom();
    }

    private void initCustom() {
       
        jListResultados.setLayout(
            new javax.swing.BoxLayout(jListResultados, javax.swing.BoxLayout.Y_AXIS)
        );

        txtBuscar.addActionListener(e -> ejecutarBusqueda());
    }

private void ejecutarBusqueda() {

    if (gestor == null) {
        return;
    }

    String filtro = txtBuscar.getText().trim().toLowerCase();

    // Limpiar resultados anteriores
    jListResultados.removeAll();
    jListResultados.revalidate();
    jListResultados.repaint();

    if (filtro.isEmpty()) {
        return;
    }

    java.util.List<Estudiante> lista = gestor.obtenerEstudiantes();

    if (lista == null || lista.isEmpty()) {
        return;
    }

    int contador = 0;

    for (Estudiante e : lista) {
        if (e == null) continue;

        String nombre  = e.getNombre()  != null ? e.getNombre().toLowerCase()  : "";
        String carrera = e.getCarrera() != null ? e.getCarrera().toLowerCase() : "";

        // Coincide por nombre o por carrera
        if (nombre.contains(filtro) || carrera.contains(filtro)) {

            // Aquí se une la clase DiseñoBusqueda
            DiseñoBusqueda item = new DiseñoBusqueda(this, e);
            jListResultados.add(item);
            contador++;
        }
    }

    jListResultados.revalidate();
    jListResultados.repaint();
}

   

    // initComponents() y declarations se quedan tal cual los generó NetBeans

   

   
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListResultados = new javax.swing.JList<>();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(240, 233, 248));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 50, -1, -1));

        txtBuscar.setBackground(new java.awt.Color(240, 233, 255));
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        jPanel12.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 780, 35));

        jListResultados.setToolTipText("");
        jListResultados.setAutoscrolls(false);
        jListResultados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(jListResultados);

        jPanel12.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 780, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 978, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtBuscar.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<Estudiante> jListResultados;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}

