/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.feeedgrow.vista;

import com.mycompany.feeedgrow.modelo.Estudiante;
import com.mycompany.feeedgrow.modelo.GestorDatos;
import java.util.Locale;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.SwingUtilities;

public class DiseñoBusqueda extends javax.swing.JPanel {
    private Estudiante estudiante;
    private Busqueda busqueda;
   

    public DiseñoBusqueda(Busqueda busqueda, Estudiante estudiante) {
        this.estudiante = estudiante;
        this.busqueda = busqueda;
        initComponents();
        cargarDatos();

        // Toda la tarjeta es clicable
        this.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (DiseñoBusqueda.this.estudiante != null) {
                    abrirIrAPerfil(DiseñoBusqueda.this.estudiante);
                }
            }
        });
    }

    private void cargarDatos() {
        if (estudiante == null) return;

        nombre.setText(estudiante.getNombre());

        String carrera = estudiante.getCarrera() != null ? estudiante.getCarrera() : "";
        String correo  = estudiante.getCorreo()  != null ? estudiante.getCorreo()  : "";

        jcarrera.setText("Carrera • " + carrera);

        String extra = "";
        double score = 0.0;

        try {
            if (estudiante.getPerfil() != null) {
                String[] attrs = estudiante.getPerfil().getMejoresAtributos();
                if (attrs != null && attrs.length > 0 && attrs[0] != null) {
                    extra = attrs[0];
                }
                score = estudiante.getPerfil().getPromedioGlobal();
            }
        } catch (Exception ignored) { }

        if (score > 0) {
            jLabel3.setText(String.format(Locale.US, "%.1f", score));
        } else {
            jLabel3.setText(""+ estudiante.getPromedioGlobal());
        }
    }

    // 👉 Aquí es donde se cambia al NUEVO panel "IrAPerfil"
    private void abrirIrAPerfil(Estudiante objetivo) {
        java.awt.Window w = SwingUtilities.getWindowAncestor(this);

        if (w instanceof PáginaMenú) {   // tu JFrame principal
            PáginaMenú frame = (PáginaMenú) w;

            irAPerfil panel = new irAPerfil(objetivo);  // NUEVO PANEL
            frame.cambiarPanel(panel);
        } else {
            
        }
    }



    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        jcarrera = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Captura de pantalla 2025-11-16 151912.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        nombre.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        nombre.setText("{estudiante nombre}");
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, 36));

        jcarrera.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcarrera.setText("Carrera • {estudiante carrera}");
        jPanel1.add(jcarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Captura de pantalla 2025-11-11 220725.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jcarrera;
    private javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables
}
