
package com.mycompany.feeedgrow.vista;


import com.mycompany.feeedgrow.controlador.BusquedaControlador;
import com.mycompany.feeedgrow.modelo.Estudiante;
import com.mycompany.feeedgrow.persistencia.GestorDatos;
import java.awt.Color;
import static java.awt.Component.CENTER_ALIGNMENT;
import java.awt.Dimension;
import java.awt.Font;
import java.util.List;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

public class GestorMisCalificaciones extends javax.swing.JPanel {
private Estudiante usuario;
private GestorDatos gestor;

   
    public GestorMisCalificaciones(Estudiante usuario, GestorDatos gestor) {
        this.gestor = gestor;
        this.usuario = usuario;
        initComponents();
        initCustom();
    }
 private void initCustom() {
       
        jPanel1.setLayout(
            new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS)
        );

        campoBusqueda.addActionListener(e -> ejecutarBusqueda());
    }


  private void ejecutarBusqueda() {
  BusquedaControlador controlador = new BusquedaControlador();
    String nombre = campoBusqueda.getText().trim();
    String carrera = (String) jSeleccionadorDeCarrera.getSelectedItem();
    jPanel1.removeAll();
    jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));
    jPanel1.setAlignmentX(LEFT_ALIGNMENT);
    List<Estudiante> resultados =
            controlador.buscar(nombre, carrera, usuario,
                               gestor.buscarEstudiantesCalificadosPorEvaluador(usuario));
    if (resultados.isEmpty()) {
        JLabel mensaje = new JLabel("No hay resultados encontrados", SwingConstants.CENTER);
        mensaje.setForeground(Color.GRAY);
        mensaje.setFont(new Font("Arial", Font.ITALIC, 16));
        mensaje.setAlignmentX(CENTER_ALIGNMENT);
        jPanel1.add(Box.createVerticalGlue());
        jPanel1.add(mensaje);
        jPanel1.add(Box.createVerticalGlue());
    } else {
        for (Estudiante e : resultados) {

            ItemGestor item = new ItemGestor(usuario, gestor, e);
            item.setAlignmentX(LEFT_ALIGNMENT);
            item.setMaximumSize(
                new Dimension(Integer.MAX_VALUE, item.getPreferredSize().height)
            );

            jPanel1.add(item);
        }
    }

    jPanel1.revalidate();
    jPanel1.repaint();
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBuscar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListResultados = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoBusqueda = new javax.swing.JTextField();
        jSeleccionadorDeCarrera = new javax.swing.JComboBox<>();
        jBotonBuscar = new javax.swing.JButton();
        jBotonLimipiarBusqueda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        txtBuscar.setBackground(new java.awt.Color(240, 233, 255));
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        jListResultados.setToolTipText("");
        jListResultados.setAutoscrolls(false);
        jListResultados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(jListResultados);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel1.setText("Mis Calificaciones");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 600, -1));

        campoBusqueda.setBackground(new java.awt.Color(250, 236, 252));
        campoBusqueda.setText("Busque por nombre");
        campoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBusquedaActionPerformed(evt);
            }
        });
        jPanel2.add(campoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 520, 35));

        jSeleccionadorDeCarrera.setBackground(new java.awt.Color(250, 236, 252));
        jSeleccionadorDeCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione carrera", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jSeleccionadorDeCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 140, -1));

        jBotonBuscar.setText("Buscar");
        jBotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(jBotonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 80, -1, -1));

        jBotonLimipiarBusqueda.setBackground(new java.awt.Color(240, 233, 248));
        jBotonLimipiarBusqueda.setText("X");
        jBotonLimipiarBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonLimipiarBusquedaActionPerformed(evt);
            }
        });
        jPanel2.add(jBotonLimipiarBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 80, -1, -1));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setBackground(new java.awt.Color(250, 240, 252));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 822, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 840, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void campoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBusquedaActionPerformed

    private void jBotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonBuscarActionPerformed
        ejecutarBusqueda();
    }//GEN-LAST:event_jBotonBuscarActionPerformed

    private void jBotonLimipiarBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonLimipiarBusquedaActionPerformed
        campoBusqueda.setText("");
    }//GEN-LAST:event_jBotonLimipiarBusquedaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoBusqueda;
    private javax.swing.JButton jBotonBuscar;
    private javax.swing.JButton jBotonLimipiarBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<Estudiante> jListResultados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jSeleccionadorDeCarrera;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
