
package com.mycompany.feeedgrow.vista;

import com.mycompany.feeedgrow.modelo.Calificacion;
import com.mycompany.feeedgrow.modelo.Estudiante;
import com.mycompany.feeedgrow.persistencia.GestorDatos;


public class ItemGestor extends javax.swing.JPanel {
    private Calificacion calificacion;
    private GestorDatos gestor;
    private Estudiante evaluado;

    public ItemGestor(Estudiante usuario, GestorDatos gestor, Estudiante estudiante) {
        initComponents();
        this.evaluado = estudiante;
        this.calificacion = gestor.buscarCalificacionPorEvaluadorYEvaluado(usuario, estudiante);
        this.gestor = gestor;
        cargarDatos();
    }

    private void cargarDatos() {
        nombre.setText(evaluado.getNombre());
        jcarrera.setText("Carrera • " + evaluado.getCarrera());
        jAtributo.setText(calificacion.getEvaluado().getPerfil().getMejoresAtributos());
       
    }


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        jcarrera = new javax.swing.JLabel();
        botonEliminar = new javax.swing.JButton();
        botonEditar = new javax.swing.JButton();
        jAtributo = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 99));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Captura de pantalla 2025-11-16 151912.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        nombre.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        nombre.setText("{estudiante nombre}");
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 36));

        jcarrera.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcarrera.setText("Carrera • {estudiante carrera}");
        jPanel1.add(jcarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, 30));

        botonEliminar.setBackground(new java.awt.Color(255, 0, 0));
        botonEliminar.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        botonEliminar.setForeground(new java.awt.Color(30, 30, 30));
        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(botonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 100, 30));

        botonEditar.setBackground(new java.awt.Color(51, 255, 102));
        botonEditar.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        botonEditar.setForeground(new java.awt.Color(30, 30, 30));
        botonEditar.setText("Editar");
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });
        jPanel1.add(botonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 80, 30));

        jAtributo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jAtributo.setText("{calificacion atributo}");
        jPanel1.add(jAtributo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 943, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JLabel jAtributo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jcarrera;
    private javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables
}
