
package com.mycompany.feeedgrow.vista;
import com.mycompany.feeedgrow.modelo.Estudiante;
import com.mycompany.feeedgrow.persistencia.GestorDatos;
import java.awt.Color;
import java.awt.Cursor;
import java.util.Locale;
import javax.swing.SwingUtilities;

public class ItemBusqueda extends javax.swing.JPanel {
  
    private Estudiante estudiante;
    private Busqueda busqueda;
    private GestorDatos gestor;
    private Estudiante usuario;

    public ItemBusqueda(Busqueda busqueda, Estudiante usuario, Estudiante estudiante, GestorDatos gestor) {
        this.estudiante = estudiante;
        this.gestor = gestor;
        this.busqueda = busqueda;
        this.usuario = usuario;
        initComponents(); 
        initCustom();     
    }

    private void initCustom() {
        cargarDatos();
        configurarNombreClicable();
    }

    private void cargarDatos() {
        if (estudiante == null) return;

        nombre.setText(estudiante.getNombre());

        String carrera = estudiante.getCarrera() != null ? estudiante.getCarrera() : "";
        jCarrera.setText("Carrera • " + carrera);

        double score = 0.0;
        String attrs = "";

        if (estudiante.getPerfil() != null) {
            try {
                attrs = estudiante.getPerfil().getMejoresAtributos();
                score = estudiante.getPerfil().getPromedioGlobal();
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        }

        jMejoresAtributos.setText(attrs);

        // Mostrar promedio con coma decimal en español
        jLabel3.setText(String.format(Locale.forLanguageTag("es-CO"), "%.1f", score));
    }

    private void configurarNombreClicable() {
        nombre.setForeground(Color.BLACK);
        nombre.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirPerfil();
            }

            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nombre.setForeground(Color.BLUE);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nombre.setForeground(Color.BLACK);
            }
        });
    }

    private void abrirPerfil() {
        java.awt.Window w = SwingUtilities.getWindowAncestor(this);

        if (w instanceof PáginaMenú) {
            PáginaMenú frame = (PáginaMenú) w;
            PerfilOtro panel = new PerfilOtro(usuario, gestor, estudiante);
            frame.cambiarPanel(panel);
        }
    }



    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        jMejoresAtributos = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCarrera = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Captura de pantalla 2025-11-16 151912.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        nombre.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        nombre.setText("{estudiante nombre}");
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, 36));

        jMejoresAtributos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMejoresAtributos.setText("{mejores atributos}");
        jPanel1.add(jMejoresAtributos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Captura de pantalla 2025-11-11 220725.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, 50));

        jCarrera.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCarrera.setText("Carrera • {estudiante carrera}");
        jPanel1.add(jCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jCarrera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jMejoresAtributos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables
}
