
package com.mycompany.feeedgrow.vista;

public class ItemRecomendacion extends javax.swing.JPanel {
private String titulo;
private String cuerpo;
    public ItemRecomendacion(String tituloRecomendacion, String recomendacion) {
        this.titulo = tituloRecomendacion;
        this.cuerpo = recomendacion;
        initComponents();
        cargarDatos();
    }

     private void cargarDatos() {
        textoTitulo.setText(titulo);
        textoCuerpo.setText(cuerpo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        textoTitulo = new javax.swing.JLabel();
        textoCuerpo = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();

        fondo.setBackground(new java.awt.Color(255, 255, 255));

        textoTitulo.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        textoTitulo.setForeground(new java.awt.Color(29, 27, 32));
        textoTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textoTitulo.setText("{ titulo recomendacion}");

        textoCuerpo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        textoCuerpo.setForeground(new java.awt.Color(73, 69, 79));
        textoCuerpo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textoCuerpo.setText("{cuerpo recomendacion}");
        textoCuerpo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        separador.setForeground(new java.awt.Color(202, 196, 208));

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textoTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
                    .addComponent(textoCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(separador)
                .addContainerGap())
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fondo;
    private javax.swing.JSeparator separador;
    private javax.swing.JLabel textoCuerpo;
    private javax.swing.JLabel textoTitulo;
    // End of variables declaration//GEN-END:variables
}
