/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.feeedgrow.vista;

import com.mycompany.feeedgrow.modelo.Calificación;
import com.mycompany.feeedgrow.modelo.Estudiante;

/**
 *
 * @author PC
 */
public class ItemCalificación extends javax.swing.JPanel {

    private Calificación calificacion;
    private Gestor parent;

    public ItemCalificación(Calificación c, Gestor parent) {
        initComponents();
        this.calificacion = c;
        this.parent = parent;
        cargarDatos();
    }

    private void cargarDatos() {
        Estudiante e = calificacion.getEvaluado();

        nombre.setText(e.getNombre());
        jcarrera.setText("Carrera • " + e.getCarrera());
        jAtributo.setText(calificacion.getAtributo());
       
    }


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        jcarrera = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jAtributo = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Captura de pantalla 2025-11-16 151912.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        nombre.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        nombre.setText("{estudiante nombre}");
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 36));

        jcarrera.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcarrera.setText("Carrera • {estudiante carrera}");
        jPanel1.add(jcarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, 30));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, 80, 30));

        jButton2.setBackground(new java.awt.Color(51, 255, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 80, 30));

        jAtributo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jAtributo.setText("{calificacion atributo}");
        jPanel1.add(jAtributo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 958, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAtributo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jcarrera;
    private javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables
}
