/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.feeedgrow.vista;

import com.mycompany.feeedgrow.modelo.Estudiante;
import java.util.Arrays;
import java.util.Locale;

/**
 *
 * @author micha
 */
public class ItemRanking extends javax.swing.JPanel {
private Estudiante estudiante;
    /**
     * Creates new form ItemRanking
     */
    public ItemRanking(Estudiante estudiante) {
        initComponents();
        this.estudiante = estudiante;
        initCustom();
    }
private void initCustom() {
        if (estudiante == null) return;

        
       nombre1.setText(estudiante.getNombre());
        jCarrera1.setText("Carrera • " + estudiante.getCarrera());

        
        if (estudiante.getPerfil() != null) {
            var perfil = estudiante.getPerfil();

            
            double score = perfil.getPromedioGlobal();
            jLabel4.setText(String.format(Locale.US, "%.1f", score));

            
            String attrs = perfil.getMejoresAtributos();
            if (attrs != null && !attrs.isBlank()) {
             jMejoresAtributos1.setText(attrs);
            } else {
                jMejoresAtributos1.setText("");
            }
        } else {
            jLabel4.setText("—");
            jMejoresAtributos1.setText("");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        jMejoresAtributos = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCarrera = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nombre1 = new javax.swing.JLabel();
        jMejoresAtributos1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCarrera1 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Captura de pantalla 2025-11-16 151912.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        nombre.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        nombre.setText("{estudiante nombre}");
        jPanel2.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, 36));

        jMejoresAtributos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMejoresAtributos.setText("{mejores atributos}");
        jPanel2.add(jMejoresAtributos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Captura de pantalla 2025-11-11 220725.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, 50));

        jCarrera.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCarrera.setText("Carrera • {estudiante carrera}");
        jPanel2.add(jCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Captura de pantalla 2025-11-16 151912.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        nombre1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        nombre1.setText("{estudiante nombre}");
        jPanel3.add(nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, 36));

        jMejoresAtributos1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMejoresAtributos1.setText("{mejores atributos}");
        jPanel3.add(jMejoresAtributos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 410, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Captura de pantalla 2025-11-11 220725.png"))); // NOI18N
        jLabel4.setText("jLabel3");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, 50));

        jCarrera1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCarrera1.setText("Carrera • {estudiante carrera}");
        jPanel3.add(jCarrera1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jCarrera;
    private javax.swing.JLabel jCarrera1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jMejoresAtributos;
    private javax.swing.JLabel jMejoresAtributos1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel nombre1;
    // End of variables declaration//GEN-END:variables
}
