
package com.mycompany.feeedgrow.vista;
import com.mycompany.feeedgrow.controlador.PerfilControlador;
import com.mycompany.feeedgrow.modelo.CriterioEvaluacion;
import com.mycompany.feeedgrow.modelo.Estudiante;
import com.mycompany.feeedgrow.persistencia.GestorDatos;
import java.awt.BorderLayout;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.Locale;
import javax.swing.JPanel;



/**
 *
 * @author PC
 */
public class MiPerfil extends javax.swing.JPanel {
private Estudiante usuario;
private GestorDatos gestor;

    public MiPerfil(Estudiante usuario, GestorDatos gestor) {
        this.usuario = usuario;
        this.gestor = gestor;
        initComponents();
        initCustom();
        cargarPromedios();
        
    }
    public void initCustom(){
        textoCarrera.setText("Carrera • " + usuario.getCarrera());
        jLabel11.setText(usuario.getNombre());
        textoCorreo.setText("Correo: " + usuario.getCorreo());
        textoAtributos.setText("Atributos: " + usuario.getPerfil().getMejoresAtributos());
    }
    public void cambiarPanel(JPanel p) {
        fondo11.removeAll();
        fondo11.setLayout(new java.awt.BorderLayout());
        fondo11.add(p, BorderLayout.CENTER);
        fondo11.revalidate();
        fondo11.repaint();
        
    }


    private static final DecimalFormat DF =
    new DecimalFormat("#0.0", new DecimalFormatSymbols(new Locale("es", "CO")));

private void setScore(javax.swing.JLabel label, double valor) {
    label.setText(DF.format(valor)); 
}

public void cargarPromedios() {
    PerfilControlador pc = new PerfilControlador(gestor); // inyecta gestor si ya lo tienes

    setScore(textoPromedioResponsabilidad, pc.getPromedio(usuario, CriterioEvaluacion.RESPONSABILIDAD));
    setScore(jLabel28, pc.getPromedio(usuario, CriterioEvaluacion.COLABORACION));
    setScore(jLabel29, pc.getPromedio(usuario, CriterioEvaluacion.COMUNICACION));
    setScore(jLabel26, pc.getPromedio(usuario, CriterioEvaluacion.PARTICIPACION));
    setScore(jLabel27, pc.getPromedio(usuario, CriterioEvaluacion.COMPROMISO));
    setScore(jLabel41, pc.getPromedio(usuario, CriterioEvaluacion.INICIATIVA));
    setScore(jLabel44, pc.getPromedio(usuario, CriterioEvaluacion.LIDERAZGO));
    setScore(jLabel39, pc.getPromedio(usuario, CriterioEvaluacion.RESOLUCION_CONFLICTOS));
    setScore(jLabel42, pc.getPromedio(usuario, CriterioEvaluacion.CONFIABILIDAD));
    setScore(jLabel48, pc.getPromedio(usuario, CriterioEvaluacion.ACTITUD));
    setScore(jLabel43, pc.getPromedioGlobal(usuario));
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        textoCarrera = new javax.swing.JLabel();
        textoCorreo = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        textoPromedioResponsabilidad = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        Responsabilidad = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        textoAtributos = new javax.swing.JLabel();

        fondo11.setBackground(new java.awt.Color(255, 255, 255));
        fondo11.setPreferredSize(new java.awt.Dimension(978, 653));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Captura de pantalla 2025-02-04 233137.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 28)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(29, 27, 32));
        jLabel11.setText("{estudiante nombre}");

        textoCarrera.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        textoCarrera.setForeground(new java.awt.Color(63, 79, 69));
        textoCarrera.setText("Carrera • {estudiante carrera}");

        textoCorreo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        textoCorreo.setForeground(new java.awt.Color(63, 79, 69));
        textoCorreo.setText("Correo: {estudiante correo}");

        jButton2.setBackground(new java.awt.Color(233, 24, 24));
        jButton2.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cerrar sesion");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(29, 27, 32));
        jLabel16.setText("Iniciativa");

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(29, 27, 32));
        jLabel15.setText("Cumple las tareas a tiempo y con calidad.");

        jLabel17.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(29, 27, 32));
        jLabel17.setText("Ayuda y aporta al trabajo conjunto.");

        jLabel19.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(29, 27, 32));
        jLabel19.setText("Nivel de involucramiento en reuniones y discusiones.");

        jLabel20.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(29, 27, 32));
        jLabel20.setText("Comunicación");

        jLabel21.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(29, 27, 32));
        jLabel21.setText("Explica claro, escucha y respesta turnos.");

        jLabel22.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(29, 27, 32));
        jLabel22.setText("Participación");

        jLabel23.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(29, 27, 32));
        jLabel23.setText("Demuestra interés y constancia en el proyecto.");

        jButton3.setBackground(new java.awt.Color(0, 204, 102));
        jButton3.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Editar perfil");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        textoPromedioResponsabilidad.setFont(new java.awt.Font("Roboto", 0, 23)); // NOI18N
        textoPromedioResponsabilidad.setForeground(new java.awt.Color(29, 27, 32));
        textoPromedioResponsabilidad.setText("0,0");

        jLabel26.setFont(new java.awt.Font("Roboto", 0, 23)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(29, 27, 32));
        jLabel26.setText("0,0");

        jLabel27.setFont(new java.awt.Font("Roboto", 0, 23)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(29, 27, 32));
        jLabel27.setText("0,0");

        jLabel28.setFont(new java.awt.Font("Roboto", 0, 23)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(29, 27, 32));
        jLabel28.setText("0,0");

        jLabel29.setFont(new java.awt.Font("Roboto", 0, 23)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(29, 27, 32));
        jLabel29.setText("0,0");

        jLabel31.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(29, 27, 32));
        jLabel31.setText("Actitud");

        jLabel37.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(29, 27, 32));
        jLabel37.setText("Compromiso");

        jLabel39.setFont(new java.awt.Font("Roboto", 0, 23)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(29, 27, 32));
        jLabel39.setText("0,0");

        jLabel40.setFont(new java.awt.Font("Segoe UI Emoji", 0, 30)); // NOI18N
        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Captura de pantalla 2025-11-11 220725.png"))); // NOI18N

        jLabel41.setFont(new java.awt.Font("Roboto", 0, 23)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(29, 27, 32));
        jLabel41.setText("0,0");

        jLabel42.setFont(new java.awt.Font("Roboto", 0, 23)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(29, 27, 32));
        jLabel42.setText("0,0");

        jLabel44.setFont(new java.awt.Font("Roboto", 0, 23)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(29, 27, 32));
        jLabel44.setText("0,0");

        Responsabilidad.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Responsabilidad.setForeground(new java.awt.Color(29, 27, 32));
        Responsabilidad.setText("Responsabilidad");

        jLabel45.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(29, 27, 32));
        jLabel45.setText("Propone ideas nuevas.");

        jLabel46.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(29, 27, 32));
        jLabel46.setText("Colaboracion");

        jLabel47.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(29, 27, 32));
        jLabel47.setText("Muestra disposición positiva, respeto y motivación.");

        jLabel32.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(29, 27, 32));
        jLabel32.setText("Liderazgo");

        jLabel49.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(29, 27, 32));
        jLabel49.setText("Motiva, organia o guía al grupo cuando es necesario.");

        jLabel33.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(29, 27, 32));
        jLabel33.setText("Resolución de conflictos");

        jLabel50.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(29, 27, 32));
        jLabel50.setText("Maneja difrencias sin generar discusiones negativas.");

        jLabel34.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(29, 27, 32));
        jLabel34.setText("Confiabilidad");

        jLabel51.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(29, 27, 32));
        jLabel51.setText("El equipo puede contar con el/ella; cumple lo que promete.");

        jLabel48.setFont(new java.awt.Font("Roboto", 0, 23)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(29, 27, 32));
        jLabel48.setText("0,0");

        jLabel43.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(29, 27, 32));
        jLabel43.setText("0,0");

        textoAtributos.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        textoAtributos.setForeground(new java.awt.Color(63, 79, 69));
        textoAtributos.setText("atributos: {atributos}");

        javax.swing.GroupLayout fondo11Layout = new javax.swing.GroupLayout(fondo11);
        fondo11.setLayout(fondo11Layout);
        fondo11Layout.setHorizontalGroup(
            fondo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondo11Layout.createSequentialGroup()
                .addGroup(fondo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondo11Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(210, 210, 210))
                    .addGroup(fondo11Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(Responsabilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(205, 205, 205)))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel41)
                .addGap(143, 143, 143))
            .addGroup(fondo11Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(fondo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondo11Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fondo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondo11Layout.createSequentialGroup()
                                .addGroup(fondo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textoCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(9, 9, 9))
                            .addGroup(fondo11Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(fondo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoAtributos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(fondo11Layout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addGap(362, 362, 362))))
                            .addComponent(textoCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel40)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel43)
                        .addGap(137, 137, 137))
                    .addGroup(fondo11Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(151, 151, 151)
                        .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(225, 225, 225))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fondo11Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(634, 634, 634))
                    .addGroup(fondo11Layout.createSequentialGroup()
                        .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(316, 316, 316))
                    .addGroup(fondo11Layout.createSequentialGroup()
                        .addGroup(fondo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondo11Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(148, 148, 148))
                            .addGroup(fondo11Layout.createSequentialGroup()
                                .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(176, 176, 176)))
                        .addGroup(fondo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondo11Layout.createSequentialGroup()
                                .addComponent(textoPromedioResponsabilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(480, 480, 480))
                            .addGroup(fondo11Layout.createSequentialGroup()
                                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(391, 391, 391)
                                .addComponent(jLabel44)
                                .addGap(143, 143, 143))
                            .addGroup(fondo11Layout.createSequentialGroup()
                                .addGroup(fondo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel26))
                                .addGap(74, 74, 74)
                                .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(fondo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel39)
                                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(121, 121, 121))))
                    .addGroup(fondo11Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(181, 181, 181)
                        .addGroup(fondo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondo11Layout.createSequentialGroup()
                                .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(264, 264, 264))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondo11Layout.createSequentialGroup()
                                .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel48)
                                .addGap(143, 143, 143))))
                    .addGroup(fondo11Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(246, 246, 246)
                        .addGroup(fondo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondo11Layout.createSequentialGroup()
                                .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(fondo11Layout.createSequentialGroup()
                                .addComponent(jLabel49, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(257, 257, 257))
                            .addGroup(fondo11Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(fondo11Layout.createSequentialGroup()
                                .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(fondo11Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(216, 216, 216)
                        .addGroup(fondo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondo11Layout.createSequentialGroup()
                                .addComponent(jLabel50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(254, 254, 254))
                            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        fondo11Layout.setVerticalGroup(
            fondo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondo11Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(fondo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fondo11Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(textoCarrera)
                        .addGap(8, 8, 8)
                        .addComponent(textoCorreo)
                        .addGap(8, 8, 8)
                        .addComponent(textoAtributos)
                        .addGap(8, 8, 8)
                        .addComponent(jButton3))
                    .addGroup(fondo11Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel40))
                    .addGroup(fondo11Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel43)))
                .addGap(72, 72, 72)
                .addGroup(fondo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondo11Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(Responsabilidad))
                    .addGroup(fondo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(textoPromedioResponsabilidad))
                    .addComponent(jLabel41))
                .addGap(2, 2, 2)
                .addGroup(fondo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel45))
                .addGap(15, 15, 15)
                .addGroup(fondo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel46)
                    .addGroup(fondo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28)
                        .addComponent(jLabel32))
                    .addComponent(jLabel44))
                .addGap(2, 2, 2)
                .addGroup(fondo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel49))
                .addGap(15, 15, 15)
                .addGroup(fondo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel29)
                    .addGroup(fondo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel39)
                        .addComponent(jLabel33)))
                .addGap(2, 2, 2)
                .addGroup(fondo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel50))
                .addGap(10, 10, 10)
                .addGroup(fondo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addGroup(fondo11Layout.createSequentialGroup()
                        .addGroup(fondo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addGroup(fondo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel42)
                                .addComponent(jLabel34)))
                        .addGap(2, 2, 2)
                        .addGroup(fondo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel51))
                        .addGroup(fondo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondo11Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(fondo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel37)
                                    .addComponent(jLabel26)))
                            .addGroup(fondo11Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(fondo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel48))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fondo11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel47))
                        .addGap(32, 32, 32)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondo11, javax.swing.GroupLayout.DEFAULT_SIZE, 984, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo11, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        javax.swing.JOptionPane.showMessageDialog(this,
            "Cierre de sesión exitoso. " + usuario.getNombre() + "!",
            "Hasta luego",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
            javax.swing.JFrame frameActual = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
            frameActual.dispose();
            InicioDeSesion inicio = new InicioDeSesion(gestor);
            inicio.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        cambiarPanel (new EditarPerfil(gestor, usuario));
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Responsabilidad;
    private javax.swing.JPanel fondo11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel textoAtributos;
    private javax.swing.JLabel textoCarrera;
    private javax.swing.JLabel textoCorreo;
    private javax.swing.JLabel textoPromedioResponsabilidad;
    // End of variables declaration//GEN-END:variables
}
