
package com.mycompany.feeedgrow.vista;
import com.mycompany.feeedgrow.controlador.PerfilControlador;
import com.mycompany.feeedgrow.modelo.CriterioEvaluacion;
import com.mycompany.feeedgrow.modelo.Estudiante;
import com.mycompany.feeedgrow.persistencia.GestorDatos;
import java.awt.BorderLayout;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.Locale;
import javax.swing.JPanel;



/**
 *
 * @author PC
 */
public class MiPerfil extends javax.swing.JPanel {
private Estudiante usuario;
private GestorDatos gestor;

    public MiPerfil(Estudiante usuario, GestorDatos gestor) {
        this.usuario = usuario;
        this.gestor = gestor;
        initComponents();
        initCustom();
        cargarPromedios();
        
    }
    public void initCustom(){
        carrera.setText("Carrera • " + usuario.getCarrera());
        nombre.setText(usuario.getNombre());
        correo.setText("Correo: " + usuario.getCorreo());
        atributos.setText("Atributos: " + usuario.getPerfil().getMejoresAtributos());
    }
    public void cambiarPanel(JPanel p) {
        fondo.removeAll();
        fondo.setLayout(new java.awt.BorderLayout());
        fondo.add(p, BorderLayout.CENTER);
        fondo.revalidate();
        fondo.repaint();
        
    }


    private static final DecimalFormat DF =
    new DecimalFormat("#0.0", new DecimalFormatSymbols(new Locale("es", "CO")));

private void setScore(javax.swing.JLabel label, double valor) {
    label.setText(DF.format(valor)); 
}

public void cargarPromedios() {
    PerfilControlador pc = new PerfilControlador(gestor); // inyecta gestor si ya lo tienes

    setScore(textoPromedioResponsabilidad, pc.getPromedio(usuario, CriterioEvaluacion.RESPONSABILIDAD));
    setScore(jColaboracion, pc.getPromedio(usuario, CriterioEvaluacion.COLABORACION));
    setScore(jComunicaicon, pc.getPromedio(usuario, CriterioEvaluacion.COMUNICACION));
    setScore(jCompromiso, pc.getPromedio(usuario, CriterioEvaluacion.PARTICIPACION));
    setScore(jParticipacion, pc.getPromedio(usuario, CriterioEvaluacion.COMPROMISO));
    setScore(jLabel41, pc.getPromedio(usuario, CriterioEvaluacion.INICIATIVA));
    setScore(jLabel44, pc.getPromedio(usuario, CriterioEvaluacion.LIDERAZGO));
    setScore(jLabel39, pc.getPromedio(usuario, CriterioEvaluacion.RESOLUCION_CONFLICTOS));
    setScore(jLabel42, pc.getPromedio(usuario, CriterioEvaluacion.CONFIABILIDAD));
    setScore(jLabel48, pc.getPromedio(usuario, CriterioEvaluacion.ACTITUD));
    setScore(promedio, pc.getPromedioGlobal(usuario));
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        iconoUsuario = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        carrera = new javax.swing.JLabel();
        correo = new javax.swing.JLabel();
        botonCerrarSesion = new javax.swing.JButton();
        Iniciativa = new javax.swing.JLabel();
        descripcionResponsabilidad = new javax.swing.JLabel();
        descripcionColaboracion = new javax.swing.JLabel();
        descripcionParticipacion = new javax.swing.JLabel();
        comunicacion = new javax.swing.JLabel();
        descripcionComunicacion = new javax.swing.JLabel();
        Participacion = new javax.swing.JLabel();
        descripcionCompromiso = new javax.swing.JLabel();
        botonEditar = new javax.swing.JButton();
        textoPromedioResponsabilidad = new javax.swing.JLabel();
        jCompromiso = new javax.swing.JLabel();
        jParticipacion = new javax.swing.JLabel();
        jColaboracion = new javax.swing.JLabel();
        jComunicaicon = new javax.swing.JLabel();
        actitud = new javax.swing.JLabel();
        Compromiso = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        iconoEstrella = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        Responsabilidad = new javax.swing.JLabel();
        descripcionIniciatia = new javax.swing.JLabel();
        colaboracion = new javax.swing.JLabel();
        descripcionActitud = new javax.swing.JLabel();
        liderazgo = new javax.swing.JLabel();
        descripcionLiderazgo = new javax.swing.JLabel();
        resolucion = new javax.swing.JLabel();
        descripcionResolucion = new javax.swing.JLabel();
        confiabilidad = new javax.swing.JLabel();
        descripcionConfiabilidad = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        promedio = new javax.swing.JLabel();
        atributos = new javax.swing.JLabel();

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setPreferredSize(new java.awt.Dimension(978, 653));

        iconoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Captura de pantalla 2025-02-04 233137.png"))); // NOI18N

        nombre.setFont(new java.awt.Font("Roboto", 0, 28)); // NOI18N
        nombre.setForeground(new java.awt.Color(29, 27, 32));
        nombre.setText("{estudiante nombre}");

        carrera.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        carrera.setForeground(new java.awt.Color(63, 79, 69));
        carrera.setText("Carrera • {estudiante carrera}");

        correo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        correo.setForeground(new java.awt.Color(63, 79, 69));
        correo.setText("Correo: {estudiante correo}");

        botonCerrarSesion.setBackground(new java.awt.Color(233, 24, 24));
        botonCerrarSesion.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        botonCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        botonCerrarSesion.setText("Cerrar sesion");
        botonCerrarSesion.setBorder(null);
        botonCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarSesionActionPerformed(evt);
            }
        });

        Iniciativa.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Iniciativa.setForeground(new java.awt.Color(29, 27, 32));
        Iniciativa.setText("Iniciativa");

        descripcionResponsabilidad.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        descripcionResponsabilidad.setForeground(new java.awt.Color(63, 79, 69));
        descripcionResponsabilidad.setText("Cumple las tareas a tiempo y con calidad.");

        descripcionColaboracion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        descripcionColaboracion.setForeground(new java.awt.Color(63, 79, 69));
        descripcionColaboracion.setText("Ayuda y aporta al trabajo conjunto.");

        descripcionParticipacion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        descripcionParticipacion.setForeground(new java.awt.Color(63, 79, 69));
        descripcionParticipacion.setText("Nivel de involucramiento en reuniones y discusiones.");

        comunicacion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        comunicacion.setForeground(new java.awt.Color(29, 27, 32));
        comunicacion.setText("Comunicación");

        descripcionComunicacion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        descripcionComunicacion.setForeground(new java.awt.Color(63, 79, 69));
        descripcionComunicacion.setText("Explica claro, escucha y respesta turnos.");

        Participacion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Participacion.setForeground(new java.awt.Color(29, 27, 32));
        Participacion.setText("Participación");

        descripcionCompromiso.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        descripcionCompromiso.setForeground(new java.awt.Color(63, 79, 69));
        descripcionCompromiso.setText("Demuestra interés y constancia en el proyecto.");

        botonEditar.setBackground(new java.awt.Color(0, 204, 102));
        botonEditar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        botonEditar.setForeground(new java.awt.Color(255, 255, 255));
        botonEditar.setText("Editar perfil");
        botonEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });

        textoPromedioResponsabilidad.setFont(new java.awt.Font("Roboto", 0, 23)); // NOI18N
        textoPromedioResponsabilidad.setForeground(new java.awt.Color(29, 27, 32));
        textoPromedioResponsabilidad.setText("0,0");

        jCompromiso.setFont(new java.awt.Font("Roboto", 0, 23)); // NOI18N
        jCompromiso.setForeground(new java.awt.Color(29, 27, 32));
        jCompromiso.setText("0,0");

        jParticipacion.setFont(new java.awt.Font("Roboto", 0, 23)); // NOI18N
        jParticipacion.setForeground(new java.awt.Color(29, 27, 32));
        jParticipacion.setText("0,0");

        jColaboracion.setFont(new java.awt.Font("Roboto", 0, 23)); // NOI18N
        jColaboracion.setForeground(new java.awt.Color(29, 27, 32));
        jColaboracion.setText("0,0");

        jComunicaicon.setFont(new java.awt.Font("Roboto", 0, 23)); // NOI18N
        jComunicaicon.setForeground(new java.awt.Color(29, 27, 32));
        jComunicaicon.setText("0,0");

        actitud.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        actitud.setForeground(new java.awt.Color(29, 27, 32));
        actitud.setText("Actitud");

        Compromiso.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Compromiso.setForeground(new java.awt.Color(29, 27, 32));
        Compromiso.setText("Compromiso");

        jLabel39.setFont(new java.awt.Font("Roboto", 0, 23)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(29, 27, 32));
        jLabel39.setText("0,0");

        iconoEstrella.setFont(new java.awt.Font("Segoe UI Emoji", 0, 30)); // NOI18N
        iconoEstrella.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Captura de pantalla 2025-11-11 220725.png"))); // NOI18N

        jLabel41.setFont(new java.awt.Font("Roboto", 0, 23)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(29, 27, 32));
        jLabel41.setText("0,0");

        jLabel42.setFont(new java.awt.Font("Roboto", 0, 23)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(29, 27, 32));
        jLabel42.setText("0,0");

        jLabel44.setFont(new java.awt.Font("Roboto", 0, 23)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(29, 27, 32));
        jLabel44.setText("0,0");

        Responsabilidad.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Responsabilidad.setForeground(new java.awt.Color(29, 27, 32));
        Responsabilidad.setText("Responsabilidad");

        descripcionIniciatia.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        descripcionIniciatia.setForeground(new java.awt.Color(63, 79, 69));
        descripcionIniciatia.setText("Propone ideas nuevas.");

        colaboracion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        colaboracion.setForeground(new java.awt.Color(29, 27, 32));
        colaboracion.setText("Colaboracion");

        descripcionActitud.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        descripcionActitud.setForeground(new java.awt.Color(63, 79, 69));
        descripcionActitud.setText("Muestra disposición positiva, respeto y motivación.");

        liderazgo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        liderazgo.setForeground(new java.awt.Color(29, 27, 32));
        liderazgo.setText("Liderazgo");

        descripcionLiderazgo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        descripcionLiderazgo.setForeground(new java.awt.Color(63, 79, 69));
        descripcionLiderazgo.setText("Motiva, organia o guía al grupo cuando es necesario.");

        resolucion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        resolucion.setForeground(new java.awt.Color(29, 27, 32));
        resolucion.setText("Resolución de conflictos");

        descripcionResolucion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        descripcionResolucion.setForeground(new java.awt.Color(63, 79, 69));
        descripcionResolucion.setText("Maneja difrencias sin generar discusiones negativas.");

        confiabilidad.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        confiabilidad.setForeground(new java.awt.Color(29, 27, 32));
        confiabilidad.setText("Confiabilidad");

        descripcionConfiabilidad.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        descripcionConfiabilidad.setForeground(new java.awt.Color(63, 79, 69));
        descripcionConfiabilidad.setText("El equipo puede contar con el/ella; cumple lo que promete.");

        jLabel48.setFont(new java.awt.Font("Roboto", 0, 23)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(29, 27, 32));
        jLabel48.setText("0,0");

        promedio.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        promedio.setForeground(new java.awt.Color(29, 27, 32));
        promedio.setText("0,0");

        atributos.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        atributos.setForeground(new java.awt.Color(63, 79, 69));
        atributos.setText("atributos: {atributos}");

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(descripcionResponsabilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(210, 210, 210))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(Responsabilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(205, 205, 205)))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel41)
                .addGap(143, 143, 143))
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(iconoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(carrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(9, 9, 9))
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(atributos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(fondoLayout.createSequentialGroup()
                                        .addComponent(botonEditar)
                                        .addGap(362, 362, 362))))
                            .addComponent(correo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(iconoEstrella)
                        .addGap(27, 27, 27)
                        .addComponent(promedio)
                        .addGap(137, 137, 137))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(descripcionParticipacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(151, 151, 151)
                        .addComponent(descripcionConfiabilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(225, 225, 225))
                    .addComponent(botonCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(Participacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(634, 634, 634))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(Compromiso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(316, 316, 316))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(comunicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(148, 148, 148))
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(colaboracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(176, 176, 176)))
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(textoPromedioResponsabilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(480, 480, 480))
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(jColaboracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(391, 391, 391)
                                .addComponent(jLabel44)
                                .addGap(143, 143, 143))
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jParticipacion)
                                    .addComponent(jComunicaicon)
                                    .addComponent(jCompromiso))
                                .addGap(74, 74, 74)
                                .addComponent(confiabilidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel39)
                                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(121, 121, 121))))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(descripcionCompromiso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(181, 181, 181)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(descripcionActitud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(264, 264, 264))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                                .addComponent(actitud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel48)
                                .addGap(143, 143, 143))))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(descripcionColaboracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(246, 246, 246)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(liderazgo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(descripcionLiderazgo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(257, 257, 257))
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(Iniciativa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(descripcionIniciatia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(descripcionComunicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(216, 216, 216)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(descripcionResolucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(254, 254, 254))
                            .addComponent(resolucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(carrera)
                        .addGap(8, 8, 8)
                        .addComponent(correo)
                        .addGap(8, 8, 8)
                        .addComponent(atributos)
                        .addGap(8, 8, 8)
                        .addComponent(botonEditar))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(iconoEstrella))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(promedio)))
                .addGap(72, 72, 72)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(Responsabilidad))
                    .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Iniciativa)
                        .addComponent(textoPromedioResponsabilidad))
                    .addComponent(jLabel41))
                .addGap(2, 2, 2)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descripcionResponsabilidad)
                    .addComponent(descripcionIniciatia))
                .addGap(15, 15, 15)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(colaboracion)
                    .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jColaboracion)
                        .addComponent(liderazgo))
                    .addComponent(jLabel44))
                .addGap(2, 2, 2)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descripcionColaboracion)
                    .addComponent(descripcionLiderazgo))
                .addGap(15, 15, 15)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comunicacion)
                    .addComponent(jComunicaicon)
                    .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel39)
                        .addComponent(resolucion)))
                .addGap(2, 2, 2)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descripcionComunicacion)
                    .addComponent(descripcionResolucion))
                .addGap(10, 10, 10)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jParticipacion)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Participacion)
                            .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel42)
                                .addComponent(confiabilidad)))
                        .addGap(2, 2, 2)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descripcionParticipacion)
                            .addComponent(descripcionConfiabilidad))
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Compromiso)
                                    .addComponent(jCompromiso)))
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(actitud)
                                    .addComponent(jLabel48))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descripcionCompromiso)
                            .addComponent(descripcionActitud))
                        .addGap(32, 32, 32)
                        .addComponent(botonCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 984, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarSesionActionPerformed
        
        javax.swing.JOptionPane.showMessageDialog(this,
            "Cierre de sesión exitoso. " + usuario.getNombre() + "!",
            "Hasta luego",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
            javax.swing.JFrame frameActual = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
            frameActual.dispose();
            InicioDeSesion inicio = new InicioDeSesion(gestor);
            inicio.setVisible(true);
        
    }//GEN-LAST:event_botonCerrarSesionActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        cambiarPanel (new EditarPerfil(gestor, usuario));
    }//GEN-LAST:event_botonEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Compromiso;
    private javax.swing.JLabel Iniciativa;
    private javax.swing.JLabel Participacion;
    private javax.swing.JLabel Responsabilidad;
    private javax.swing.JLabel actitud;
    private javax.swing.JLabel atributos;
    private javax.swing.JButton botonCerrarSesion;
    private javax.swing.JButton botonEditar;
    private javax.swing.JLabel carrera;
    private javax.swing.JLabel colaboracion;
    private javax.swing.JLabel comunicacion;
    private javax.swing.JLabel confiabilidad;
    private javax.swing.JLabel correo;
    private javax.swing.JLabel descripcionActitud;
    private javax.swing.JLabel descripcionColaboracion;
    private javax.swing.JLabel descripcionCompromiso;
    private javax.swing.JLabel descripcionComunicacion;
    private javax.swing.JLabel descripcionConfiabilidad;
    private javax.swing.JLabel descripcionIniciatia;
    private javax.swing.JLabel descripcionLiderazgo;
    private javax.swing.JLabel descripcionParticipacion;
    private javax.swing.JLabel descripcionResolucion;
    private javax.swing.JLabel descripcionResponsabilidad;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel iconoEstrella;
    private javax.swing.JLabel iconoUsuario;
    private javax.swing.JLabel jColaboracion;
    private javax.swing.JLabel jCompromiso;
    private javax.swing.JLabel jComunicaicon;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jParticipacion;
    private javax.swing.JLabel liderazgo;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel promedio;
    private javax.swing.JLabel resolucion;
    private javax.swing.JLabel textoPromedioResponsabilidad;
    // End of variables declaration//GEN-END:variables
}
