
package com.mycompany.feeedgrow.vista;

import com.mycompany.feeedgrow.controlador.PerfilControlador;
import com.mycompany.feeedgrow.modelo.CriterioEvaluacion;
import com.mycompany.feeedgrow.modelo.Estudiante;
import com.mycompany.feeedgrow.persistencia.GestorDatos;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.Locale;
import javax.swing.SwingUtilities;


public class PerfilOtro extends javax.swing.JPanel {
    private Estudiante estudiante;
    private Estudiante usuario;
    private GestorDatos gestor;

   
    public PerfilOtro(Estudiante usuario, GestorDatos gestor, Estudiante estudiante) {
        this.estudiante = estudiante;
        this.usuario = usuario;
        this.gestor = gestor;
        initComponents();
        cargarDatos();   
    }

 
    

    private void cargarDatos() {
        if (estudiante == null) return;
        jNombre.setText(estudiante.getNombre());
        jCarrera.setText("Carrera • " + estudiante.getCarrera());
        jCorreo.setText("Correo: " +estudiante.getCorreo());
        textoAtributos.setText("Atributos: " + estudiante.getPerfil().getMejoresAtributos());
       cargarPromedios();
    }
    private static final DecimalFormat DF =
    new DecimalFormat("#0.0", new DecimalFormatSymbols(new Locale("es", "CO")));

private void setScore(javax.swing.JLabel label, double valor) {
    label.setText(DF.format(valor)); 
}
    public void cargarPromedios() {
     PerfilControlador pc = new PerfilControlador(gestor); 

    setScore(promedioResoponsabilidad, pc.getPromedio(estudiante, CriterioEvaluacion.RESPONSABILIDAD));
    setScore(promedioColaboración, pc.getPromedio(estudiante, CriterioEvaluacion.COLABORACION));
    setScore(promedioComunicacion, pc.getPromedio(estudiante, CriterioEvaluacion.COMUNICACION));
    setScore(promedioParticipacion, pc.getPromedio(estudiante, CriterioEvaluacion.PARTICIPACION));
    setScore(promedioCompromiso, pc.getPromedio(estudiante, CriterioEvaluacion.COMPROMISO));
    setScore(promedioInciativa, pc.getPromedio(estudiante, CriterioEvaluacion.INICIATIVA));
    setScore(promedioLiderazgo, pc.getPromedio(estudiante, CriterioEvaluacion.LIDERAZGO));
    setScore(promedioResolucionDeConflictos, pc.getPromedio(estudiante, CriterioEvaluacion.RESOLUCION_CONFLICTOS));
    setScore(promedioConfiabilidad, pc.getPromedio(estudiante, CriterioEvaluacion.CONFIABILIDAD));
    setScore(promedioActitud, pc.getPromedio(estudiante, CriterioEvaluacion.ACTITUD));
    setScore(promedioGlobal, pc.getPromedioGlobal(estudiante));
}
    private void Cambiarpanel() {
        java.awt.Window w = SwingUtilities.getWindowAncestor(this);

        if (w instanceof PáginaMenú) {   
            PáginaMenú frame = (PáginaMenú) w;

            Calificar panel = new Calificar(usuario, gestor, estudiante);  
            frame.cambiarPanel(panel);
        } else {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jNombre = new javax.swing.JLabel();
        jCarrera = new javax.swing.JLabel();
        jCorreo = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        promedioResoponsabilidad = new javax.swing.JLabel();
        promedioParticipacion = new javax.swing.JLabel();
        promedioCompromiso = new javax.swing.JLabel();
        promedioColaboración = new javax.swing.JLabel();
        promedioComunicacion = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        promedioResolucionDeConflictos = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        promedioInciativa = new javax.swing.JLabel();
        promedioConfiabilidad = new javax.swing.JLabel();
        promedioLiderazgo = new javax.swing.JLabel();
        Responsabilidad = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        promedioActitud = new javax.swing.JLabel();
        promedioGlobal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        textoAtributos = new javax.swing.JLabel();

        fondo11.setBackground(new java.awt.Color(255, 255, 255));
        fondo11.setPreferredSize(new java.awt.Dimension(978, 653));
        fondo11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Captura de pantalla 2025-02-04 233137.png"))); // NOI18N
        fondo11.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 173));

        jNombre.setFont(new java.awt.Font("Segoe UI Black", 0, 28)); // NOI18N
        jNombre.setText("{estudiante nombre}");
        fondo11.add(jNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, 36));

        jCarrera.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCarrera.setText("Carrera • {estudiante carrera}");
        fondo11.add(jCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        jCorreo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCorreo.setText("Correo: {estudiante correo}");
        fondo11.add(jCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel16.setText("Iniciativa");
        fondo11.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 192, -1));

        jLabel15.setText("Cumple las tareas a tiempo y con calidad.");
        fondo11.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jLabel17.setText("Ayuda y aporta al trabajo conjunto.");
        fondo11.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jLabel19.setText("Nivel de involucramiento en reuniones y discusiones.");
        fondo11.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel20.setText("Comunicación");
        fondo11.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 192, -1));

        jLabel21.setText("Explica claro, escucha y respesta turnos.");
        fondo11.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel22.setText("Participación");
        fondo11.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 192, -1));

        jLabel23.setText("Demuestra interés y constancia en el proyecto.");
        fondo11.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        promedioResoponsabilidad.setFont(new java.awt.Font("Segoe UI Emoji", 0, 30)); // NOI18N
        promedioResoponsabilidad.setText("jLabel24");
        fondo11.add(promedioResoponsabilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, -1, -1));

        promedioParticipacion.setFont(new java.awt.Font("Segoe UI Emoji", 0, 30)); // NOI18N
        promedioParticipacion.setText("jLabel26");
        fondo11.add(promedioParticipacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, -1, -1));

        promedioCompromiso.setFont(new java.awt.Font("Segoe UI Emoji", 0, 30)); // NOI18N
        promedioCompromiso.setText("jLabel27");
        fondo11.add(promedioCompromiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, -1, -1));

        promedioColaboración.setFont(new java.awt.Font("Segoe UI Emoji", 0, 30)); // NOI18N
        promedioColaboración.setText("jLabel28");
        fondo11.add(promedioColaboración, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, -1, -1));

        promedioComunicacion.setFont(new java.awt.Font("Segoe UI Emoji", 0, 30)); // NOI18N
        promedioComunicacion.setText("jLabel29");
        fondo11.add(promedioComunicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, -1, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel31.setText("Actitud");
        fondo11.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, 270, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel37.setText("Compromiso");
        fondo11.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 192, -1));

        promedioResolucionDeConflictos.setFont(new java.awt.Font("Segoe UI Emoji", 0, 30)); // NOI18N
        promedioResolucionDeConflictos.setText("jLabel39");
        fondo11.add(promedioResolucionDeConflictos, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 400, -1, -1));

        jLabel40.setFont(new java.awt.Font("Segoe UI Emoji", 0, 30)); // NOI18N
        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Captura de pantalla 2025-11-11 220725.png"))); // NOI18N
        fondo11.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, -1, -1));

        promedioInciativa.setFont(new java.awt.Font("Segoe UI Emoji", 0, 30)); // NOI18N
        promedioInciativa.setText("jLabel41");
        fondo11.add(promedioInciativa, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 280, -1, -1));

        promedioConfiabilidad.setFont(new java.awt.Font("Segoe UI Emoji", 0, 30)); // NOI18N
        promedioConfiabilidad.setText("jLabel42");
        fondo11.add(promedioConfiabilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 460, 110, -1));

        promedioLiderazgo.setFont(new java.awt.Font("Segoe UI Emoji", 0, 30)); // NOI18N
        promedioLiderazgo.setText("jLabel44");
        fondo11.add(promedioLiderazgo, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, -1, -1));

        Responsabilidad.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        Responsabilidad.setText("Responsabilidad");
        fondo11.add(Responsabilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 282, 192, -1));

        jLabel45.setText("Propone ideas nuevas.");
        fondo11.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, -1, -1));

        jLabel46.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel46.setText("Colaboracion");
        fondo11.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel47.setText("Muestra disposición positiva, respeto y motivación.");
        fondo11.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 550, -1, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel32.setText("Liderazgo");
        fondo11.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 192, -1));

        jLabel49.setText("Motiva, organia o guía al grupo cuando es necesario.");
        fondo11.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, -1, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel33.setText("Resolución de conflictos");
        fondo11.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 270, -1));

        jLabel50.setText("Maneja difrencias sin generar discusiones negativas.");
        fondo11.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, -1, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel34.setText("Confiabilidad");
        fondo11.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, 270, -1));

        jLabel51.setText("El equipo puede contar con el/ella; cumple lo que promete.");
        fondo11.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, -1, -1));

        promedioActitud.setFont(new java.awt.Font("Segoe UI Emoji", 0, 30)); // NOI18N
        promedioActitud.setText("jLabel48");
        fondo11.add(promedioActitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 520, -1, -1));

        promedioGlobal.setFont(new java.awt.Font("Segoe UI Emoji", 0, 36)); // NOI18N
        promedioGlobal.setText("jLabel43");
        fondo11.add(promedioGlobal, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 80, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 255, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("Agregar Calificacion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        fondo11.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, -1, -1));

        textoAtributos.setText("atributos: {atributos}");
        fondo11.add(textoAtributos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 210, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondo11, javax.swing.GroupLayout.PREFERRED_SIZE, 978, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo11, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Cambiarpanel();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Responsabilidad;
    private javax.swing.JPanel fondo11;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jCarrera;
    private javax.swing.JLabel jCorreo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jNombre;
    private javax.swing.JLabel promedioActitud;
    private javax.swing.JLabel promedioColaboración;
    private javax.swing.JLabel promedioCompromiso;
    private javax.swing.JLabel promedioComunicacion;
    private javax.swing.JLabel promedioConfiabilidad;
    private javax.swing.JLabel promedioGlobal;
    private javax.swing.JLabel promedioInciativa;
    private javax.swing.JLabel promedioLiderazgo;
    private javax.swing.JLabel promedioParticipacion;
    private javax.swing.JLabel promedioResolucionDeConflictos;
    private javax.swing.JLabel promedioResoponsabilidad;
    private javax.swing.JLabel textoAtributos;
    // End of variables declaration//GEN-END:variables
}
