/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.feeedgrow.vista;

import com.mycompany.feeedgrow.modelo.Estudiante;
import com.mycompany.feeedgrow.persistencia.GestorDatos;
import java.util.List;
import javax.swing.BoxLayout;

public class Ranking extends javax.swing.JPanel {
private GestorDatos gestor;
    public Ranking(GestorDatos gestor) {
        initComponents();
        this.gestor = gestor;
        cargarRanking();
    }
    private void cargarRanking(){
         
        contenedorTop3.setLayout(new BoxLayout(contenedorTop3, BoxLayout.Y_AXIS));
        contenedorTop3.removeAll();

        if (gestor == null) return;

        List<Estudiante> top = gestor.top3();
        for (Estudiante e : top) {
            if (e == null) 
                continue;
            ItemRanking item = new ItemRanking(e);
            contenedorTop3.add(item);
        }

        contenedorTop3.revalidate();
        contenedorTop3.repaint();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fondo = new javax.swing.JPanel();
        ranking = new javax.swing.JLabel();
        contenedorTop3 = new javax.swing.JPanel();

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel1.setText("Mis Calificaciones");

        fondo.setBackground(new java.awt.Color(255, 255, 255));

        ranking.setFont(new java.awt.Font("Roboto SemiBold", 0, 48)); // NOI18N
        ranking.setForeground(new java.awt.Color(30, 30, 30));
        ranking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ranking.setText("Ranking");

        contenedorTop3.setBackground(new java.awt.Color(255, 255, 255));
        contenedorTop3.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contenedorTop3Layout = new javax.swing.GroupLayout(contenedorTop3);
        contenedorTop3.setLayout(contenedorTop3Layout);
        contenedorTop3Layout.setHorizontalGroup(
            contenedorTop3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contenedorTop3Layout.setVerticalGroup(
            contenedorTop3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(ranking, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addGap(388, 388, 388))
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(contenedorTop3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(70, 70, 70))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(ranking)
                .addGap(26, 26, 26)
                .addComponent(contenedorTop3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedorTop3;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel ranking;
    // End of variables declaration//GEN-END:variables
}
