
package com.mycompany.feeedgrow.vista;

import com.mycompany.feeedgrow.modelo.Estudiante;
import com.mycompany.feeedgrow.persistencia.GestorDatos;
import java.awt.Dimension;
import java.util.List;
import javax.swing.BoxLayout;

public class Ranking extends javax.swing.JPanel {
private GestorDatos gestor;
    public Ranking(GestorDatos gestor) {
        initComponents();
        this.gestor = gestor;
        cargarRanking();
    }
    private void cargarRanking(){
        contenedorTop3.removeAll();
        contenedorTop3.setLayout(new BoxLayout(contenedorTop3, BoxLayout.Y_AXIS));
        contenedorTop3.setAlignmentX(LEFT_ALIGNMENT);

        if (gestor == null) return;

        List<Estudiante> top = gestor.top3();
        for (Estudiante e : top) {
            if (e == null) 
                continue;
            ItemRanking item = new ItemRanking(e);
            item.setAlignmentX(LEFT_ALIGNMENT);
            item.setMaximumSize(
                new Dimension(Integer.MAX_VALUE, item.getPreferredSize().height)
            );
            contenedorTop3.add(item);
        }

        contenedorTop3.revalidate();
        contenedorTop3.repaint();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fondo = new javax.swing.JPanel();
        ranking = new javax.swing.JLabel();
        contenedorTop3 = new javax.swing.JPanel();

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel1.setText("Mis Calificaciones");

        fondo.setBackground(new java.awt.Color(255, 255, 255));

        ranking.setFont(new java.awt.Font("Roboto SemiBold", 0, 48)); // NOI18N
        ranking.setForeground(new java.awt.Color(30, 30, 30));
        ranking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ranking.setText("Ranking");

        contenedorTop3.setBackground(new java.awt.Color(255, 255, 255));
        contenedorTop3.setForeground(new java.awt.Color(255, 255, 255));
        contenedorTop3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(ranking, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addGap(388, 388, 388))
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(contenedorTop3, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(ranking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedorTop3, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedorTop3;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel ranking;
    // End of variables declaration//GEN-END:variables
}
