
package com.mycompany.feeedgrow.vista;

import com.mycompany.feeedgrow.controlador.RegistroControlador;
import com.mycompany.feeedgrow.modelo.Estudiante;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class Registro extends javax.swing.JFrame {
    
    public Registro() {
        initComponents();
        initLocation();
        initCustom();
    }
    
private void initLocation(){
    Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
    int x = (pantalla.width - this.getWidth()) / 2;
    int y = (pantalla.height - this.getHeight()) / 2;
    this.setLocation(x, y);
}
  
private void initCustom() {
    agregarDegradado(jPanel5, new Degradado(19, 188, 129, 22, 140, 202, false));
    agregarDegradado(jPanel6, new Degradado(22, 140, 202, 19, 188, 129, false));
    
}

private void agregarDegradado(JPanel destino, Degradado fondo) {
    fondo.setBounds(0, 0, destino.getWidth(), destino.getHeight());
    destino.add(fondo);
    destino.setComponentZOrder(fondo, destino.getComponentCount() - 1); // asegurarse de que el fondo quede atrás

    destino.addComponentListener(new java.awt.event.ComponentAdapter() {
        @Override
        public void componentResized(java.awt.event.ComponentEvent e) {
            fondo.setSize(destino.getSize());
        }
    });
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        título = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        campoCorreo = new javax.swing.JTextField();
        campoConfirmarContraseña = new javax.swing.JTextField();
        campoContraseña = new javax.swing.JTextField();
        campoCódigo = new javax.swing.JTextField();
        botonAceptar = new javax.swing.JButton();
        IniciarSesión = new javax.swing.JLabel();
        jComboBoxCarrera = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        jPanel3.setBackground(new java.awt.Color(30, 220, 230));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(230, 246, 246));

        jPanel2.setBackground(new java.awt.Color(230, 246, 246));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedGrow_241x86.png.png"))); // NOI18N

        título.setFont(new java.awt.Font("Roboto SemiBold", 1, 18)); // NOI18N
        título.setForeground(new java.awt.Color(102, 102, 102));
        título.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        título.setText("REGISTRO");

        campoNombre.setBackground(new java.awt.Color(255, 255, 255));
        campoNombre.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        campoNombre.setForeground(new java.awt.Color(153, 153, 153));
        campoNombre.setText("Nombre");
        campoNombre.setBorder(null);
        campoNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoNombreMouseClicked(evt);
            }
        });
        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });

        campoCorreo.setBackground(new java.awt.Color(255, 255, 255));
        campoCorreo.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        campoCorreo.setForeground(new java.awt.Color(153, 153, 153));
        campoCorreo.setText("Correo");
        campoCorreo.setBorder(null);
        campoCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoCorreoMouseClicked(evt);
            }
        });
        campoCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCorreoActionPerformed(evt);
            }
        });

        campoConfirmarContraseña.setBackground(new java.awt.Color(255, 255, 255));
        campoConfirmarContraseña.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        campoConfirmarContraseña.setForeground(new java.awt.Color(153, 153, 153));
        campoConfirmarContraseña.setText("Confirmar Contraseña");
        campoConfirmarContraseña.setBorder(null);
        campoConfirmarContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoConfirmarContraseñaMouseClicked(evt);
            }
        });

        campoContraseña.setBackground(new java.awt.Color(255, 255, 255));
        campoContraseña.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        campoContraseña.setForeground(new java.awt.Color(153, 153, 153));
        campoContraseña.setText("Contraseña");
        campoContraseña.setBorder(null);
        campoContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoContraseñaMouseClicked(evt);
            }
        });
        campoContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoContraseñaActionPerformed(evt);
            }
        });

        campoCódigo.setBackground(new java.awt.Color(255, 255, 255));
        campoCódigo.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        campoCódigo.setForeground(new java.awt.Color(153, 153, 153));
        campoCódigo.setText("Código de estudiante");
        campoCódigo.setBorder(null);
        campoCódigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoCódigoMouseClicked(evt);
            }
        });
        campoCódigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCódigoActionPerformed(evt);
            }
        });

        botonAceptar.setBackground(new java.awt.Color(49, 148, 252));
        botonAceptar.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        botonAceptar.setForeground(new java.awt.Color(255, 255, 255));
        botonAceptar.setText("Aceptar");
        botonAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAceptarMouseClicked(evt);
            }
        });
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        IniciarSesión.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        IniciarSesión.setForeground(new java.awt.Color(102, 102, 102));
        IniciarSesión.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IniciarSesión.setText("O Inciar Sesión");
        IniciarSesión.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IniciarSesión.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IniciarSesiónMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IniciarSesiónMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IniciarSesiónMouseExited(evt);
            }
        });

        jComboBoxCarrera.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxCarrera.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jComboBoxCarrera.setForeground(new java.awt.Color(153, 153, 153));
        jComboBoxCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione su carrera", "Ingeniería de Sistemas", "Ingeniería Electrónica", "Ingeniería Biomédica", "Ingeniería Química", "Biología", "Derecho", "Medicina" }));
        jComboBoxCarrera.setBorder(null);
        jComboBoxCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCarreraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(66, 66, 66))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(título, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(IniciarSesión, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6))
                            .addComponent(botonAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(8, 8, 8)))
                .addGap(151, 151, 151))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxCarrera, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoNombre)
                    .addComponent(campoCorreo)
                    .addComponent(campoConfirmarContraseña)
                    .addComponent(campoContraseña, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoCódigo, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(logo)
                .addGap(18, 18, 18)
                .addComponent(título)
                .addGap(12, 12, 12)
                .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campoCódigo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campoContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campoConfirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(botonAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IniciarSesión)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(51, 255, 204));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(51, 255, 204));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void estéticaCampos(javax.swing.JTextField campo){
    campo.setText("");
    campo.setForeground(Color.BLACK);
    if(!campo.equals(campoNombre)&& campoNombre.getText().isEmpty()){
        campoNombre.setText("Nombre");
        campoNombre.setForeground(new Color(153, 153, 153));
    }
    if(!campo.equals(campoCódigo)&& campoCódigo.getText().isEmpty()){
        campoCódigo.setText("Código de estudiante");
        campoCódigo.setForeground(new Color(153, 153, 153));
    }
    if(!campo.equals(campoCorreo)&& campoCorreo.getText().isEmpty()){
        campoCorreo.setText("Correo");
        campoCorreo.setForeground(new Color(153, 153, 153));
    }
    if(!campo.equals(campoContraseña)&& campoContraseña.getText().isEmpty()){
        campoContraseña.setText("Contraseña");
        campoContraseña.setForeground(new Color(153, 153, 153));
    }
    if(!campo.equals(campoConfirmarContraseña)&& campoConfirmarContraseña.getText().isEmpty()){
        campoConfirmarContraseña.setText("Confirmar COntraseña");
        campoConfirmarContraseña.setForeground(new Color(153, 153, 153));
    }
}
    private void campoNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoNombreMouseClicked
        estéticaCampos(campoNombre);
    }//GEN-LAST:event_campoNombreMouseClicked

    private void campoCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoCorreoMouseClicked
       estéticaCampos(campoCorreo);
    }//GEN-LAST:event_campoCorreoMouseClicked

    private void campoConfirmarContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoConfirmarContraseñaMouseClicked
        estéticaCampos(campoConfirmarContraseña);
    }//GEN-LAST:event_campoConfirmarContraseñaMouseClicked

    private void campoContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoContraseñaMouseClicked
        estéticaCampos(campoContraseña);
    }//GEN-LAST:event_campoContraseñaMouseClicked

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed

    private void campoCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCorreoActionPerformed

    private void campoCódigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoCódigoMouseClicked
        estéticaCampos(campoCódigo);
    }//GEN-LAST:event_campoCódigoMouseClicked

    private void campoCódigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCódigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCódigoActionPerformed

    private void campoContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoContraseñaActionPerformed

    private void botonAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAceptarMouseClicked

    RegistroControlador controller = new RegistroControlador();

    // Crear el objeto estudiante
    Estudiante estudiante = new Estudiante(
        campoNombre.getText().trim(),
        campoCódigo.getText().trim(),
        campoCorreo.getText().trim(),
        jComboBoxCarrera.getSelectedItem().toString(),
        campoContraseña.getText().trim()
    );

    String confirmar = campoConfirmarContraseña.getText().trim();

    // Validar datos
    String errores = controller.validarEstudiante(estudiante, confirmar);

    if (!errores.isEmpty()) {
        JOptionPane.showMessageDialog(this, errores, "Error de validación", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Registrar estudiante
    String resultado = controller.registrarEstudiante(estudiante);

    if (resultado.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Registro exitoso. ¡Bienvenido/a, " + estudiante.getNombre() + "!");
        new InicioDeSesión().setVisible(true);
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, resultado, "Error", JOptionPane.ERROR_MESSAGE);
    }
                
    }//GEN-LAST:event_botonAceptarMouseClicked

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed

    }//GEN-LAST:event_botonAceptarActionPerformed

    private void IniciarSesiónMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarSesiónMouseClicked
         InicioDeSesión ventana = new InicioDeSesión();
         ventana.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_IniciarSesiónMouseClicked

    private void IniciarSesiónMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarSesiónMouseEntered
      IniciarSesión.setForeground(new Color(22, 122, 135));
    }//GEN-LAST:event_IniciarSesiónMouseEntered

    private void IniciarSesiónMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarSesiónMouseExited
      IniciarSesión.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_IniciarSesiónMouseExited

    private void jComboBoxCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCarreraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IniciarSesión;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JTextField campoConfirmarContraseña;
    private javax.swing.JTextField campoContraseña;
    private javax.swing.JTextField campoCorreo;
    private javax.swing.JTextField campoCódigo;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JComboBox<String> jComboBoxCarrera;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel título;
    // End of variables declaration//GEN-END:variables
}
