/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.feeedgrow.vista;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author PC
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        initCustom();
    }
    private boolean validarCampos() {
    String nombre = campoNombre.getText().trim();
    String carrera = CampoCarrera.getText().trim();
    String codigo = CampoCódigo.getText().trim();
    String contraseña = CampoContraseña.getText().trim();
    String confirmar = CampoConfirmarContraseña.getText().trim();

    String[] placeholders = {
        "Nombre", "Carrera", 
        "Código de estudiante", "Contraseña", "Confirmar Contraseña"
    };

    if (nombre.isEmpty() || nombre.equalsIgnoreCase(placeholders[0])) {
        javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar su nombre completo.");
        return false;
    }

    if (codigo.isEmpty() || codigo.equalsIgnoreCase(placeholders[2])) {
        javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar su código estudiantil.");
        return false;
    }

    if (!codigo.matches("\\d+")) {
        javax.swing.JOptionPane.showMessageDialog(this, "El código solo puede contener números.");
        return false;
    }
    
    if (carrera.isEmpty() || carrera.equalsIgnoreCase(placeholders[1])) {
        javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar su carrera");
        return false;
    }


    if (contraseña.isEmpty() || contraseña.equalsIgnoreCase(placeholders[3])) {
        javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar una contraseña.");
        return false;
    }

    if (confirmar.isEmpty() || confirmar.equalsIgnoreCase(placeholders[4])) {
        javax.swing.JOptionPane.showMessageDialog(this, "Debe confirmar la contraseña.");
        return false;
    }

    if (!contraseña.equals(confirmar)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden.");
        return false;
    }

    return true;
}
    
    
private void initCustom() {
    agregarDegradado(jPanel5, new Degradado(19, 188, 129, 22, 140, 202, false));
    agregarDegradado(jPanel6, new Degradado(22, 140, 202, 19, 188, 129, false));
    
}

private void agregarDegradado(JPanel destino, Degradado fondo) {
    fondo.setBounds(0, 0, destino.getWidth(), destino.getHeight());
    destino.add(fondo);
    destino.setComponentZOrder(fondo, destino.getComponentCount() - 1); // asegurarse de que el fondo quede atrás

    destino.addComponentListener(new java.awt.event.ComponentAdapter() {
        @Override
        public void componentResized(java.awt.event.ComponentEvent e) {
            fondo.setSize(destino.getSize());
        }
    });
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        título = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        CampoCarrera = new javax.swing.JTextField();
        CampoCorreo = new javax.swing.JTextField();
        CampoConfirmarContraseña = new javax.swing.JTextField();
        CampoContraseña = new javax.swing.JTextField();
        CampoCódigo = new javax.swing.JTextField();
        botonAceptar = new javax.swing.JButton();
        IniciarSesión = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        jPanel3.setBackground(new java.awt.Color(30, 220, 230));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(230, 246, 246));

        jPanel2.setBackground(new java.awt.Color(230, 246, 246));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FeedGrow_241x86.png.png"))); // NOI18N

        título.setFont(new java.awt.Font("Roboto SemiBold", 1, 18)); // NOI18N
        título.setForeground(new java.awt.Color(102, 102, 102));
        título.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        título.setText("REGISTRO");

        campoNombre.setBackground(new java.awt.Color(255, 255, 255));
        campoNombre.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        campoNombre.setForeground(new java.awt.Color(153, 153, 153));
        campoNombre.setText("Nombre");
        campoNombre.setBorder(null);
        campoNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoNombreMouseClicked(evt);
            }
        });
        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });

        CampoCarrera.setBackground(new java.awt.Color(255, 255, 255));
        CampoCarrera.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        CampoCarrera.setForeground(new java.awt.Color(153, 153, 153));
        CampoCarrera.setText("Carrera");
        CampoCarrera.setBorder(null);
        CampoCarrera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoCarreraMouseClicked(evt);
            }
        });

        CampoCorreo.setBackground(new java.awt.Color(255, 255, 255));
        CampoCorreo.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        CampoCorreo.setForeground(new java.awt.Color(153, 153, 153));
        CampoCorreo.setText("Correo");
        CampoCorreo.setBorder(null);
        CampoCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoCorreoMouseClicked(evt);
            }
        });
        CampoCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCorreoActionPerformed(evt);
            }
        });

        CampoConfirmarContraseña.setBackground(new java.awt.Color(255, 255, 255));
        CampoConfirmarContraseña.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        CampoConfirmarContraseña.setForeground(new java.awt.Color(153, 153, 153));
        CampoConfirmarContraseña.setText("Confirmar Contraseña");
        CampoConfirmarContraseña.setBorder(null);
        CampoConfirmarContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoConfirmarContraseñaMouseClicked(evt);
            }
        });

        CampoContraseña.setBackground(new java.awt.Color(255, 255, 255));
        CampoContraseña.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        CampoContraseña.setForeground(new java.awt.Color(153, 153, 153));
        CampoContraseña.setText("Contraseña");
        CampoContraseña.setBorder(null);
        CampoContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoContraseñaMouseClicked(evt);
            }
        });
        CampoContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoContraseñaActionPerformed(evt);
            }
        });

        CampoCódigo.setBackground(new java.awt.Color(255, 255, 255));
        CampoCódigo.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        CampoCódigo.setForeground(new java.awt.Color(153, 153, 153));
        CampoCódigo.setText("Código de estudiante");
        CampoCódigo.setBorder(null);
        CampoCódigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CampoCódigoMouseClicked(evt);
            }
        });
        CampoCódigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCódigoActionPerformed(evt);
            }
        });

        botonAceptar.setBackground(new java.awt.Color(49, 148, 252));
        botonAceptar.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        botonAceptar.setForeground(new java.awt.Color(255, 255, 255));
        botonAceptar.setText("Aceptar");
        botonAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAceptarMouseClicked(evt);
            }
        });
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        IniciarSesión.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        IniciarSesión.setForeground(new java.awt.Color(102, 102, 102));
        IniciarSesión.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IniciarSesión.setText("O Inciar Sesión");
        IniciarSesión.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IniciarSesión.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IniciarSesiónMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IniciarSesiónMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IniciarSesiónMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(66, 66, 66))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CampoCarrera)
                    .addComponent(campoNombre)
                    .addComponent(CampoCorreo)
                    .addComponent(CampoConfirmarContraseña)
                    .addComponent(CampoContraseña, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CampoCódigo, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(36, 36, 36))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(título, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(IniciarSesión, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6))
                            .addComponent(botonAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(8, 8, 8)))
                .addGap(151, 151, 151))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(logo)
                .addGap(18, 18, 18)
                .addComponent(título)
                .addGap(12, 12, 12)
                .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CampoCódigo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CampoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CampoCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CampoContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CampoConfirmarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(botonAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IniciarSesión)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(51, 255, 204));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(51, 255, 204));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoNombreMouseClicked
        campoNombre.setText("");
        campoNombre.setForeground(Color.black);
    }//GEN-LAST:event_campoNombreMouseClicked

    private void CampoCarreraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoCarreraMouseClicked
       CampoCarrera.setText("");
       CampoCarrera.setForeground(Color.black);

    }//GEN-LAST:event_CampoCarreraMouseClicked

    private void CampoCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoCorreoMouseClicked
       CampoCorreo.setText("");
       CampoCorreo.setForeground(Color.black);
    }//GEN-LAST:event_CampoCorreoMouseClicked

    private void CampoConfirmarContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoConfirmarContraseñaMouseClicked
       CampoConfirmarContraseña.setText("");
       CampoConfirmarContraseña.setForeground(Color.black);
    }//GEN-LAST:event_CampoConfirmarContraseñaMouseClicked

    private void CampoContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoContraseñaMouseClicked
       CampoContraseña.setText("");
       CampoContraseña.setForeground(Color.black);
    }//GEN-LAST:event_CampoContraseñaMouseClicked

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed

    private void CampoCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCorreoActionPerformed

    private void CampoCódigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CampoCódigoMouseClicked
         CampoCódigo.setText("");
       CampoCódigo.setForeground(Color.black);
    }//GEN-LAST:event_CampoCódigoMouseClicked

    private void CampoCódigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCódigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCódigoActionPerformed

    private void CampoContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoContraseñaActionPerformed

    private void botonAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAceptarMouseClicked
                                          
    if (!validarCampos()) return; // si algo está mal, no continúa

    String codigo = CampoCódigo.getText().trim();
    String nombre = campoNombre.getText().trim();
    String correo = CampoCorreo.getText().trim();
    String carrera = CampoCarrera.getText().trim();
    String contraseña = CampoContraseña.getText().trim();

    try {
        java.io.File archivo = new java.io.File("usuarios.txt");
        archivo.createNewFile(); // si no existe lo crea
        java.util.List<String> lineas = java.nio.file.Files.readAllLines(archivo.toPath());

        for (String linea : lineas) {
            if (linea.startsWith(codigo + ",")) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Ya existe una cuenta con ese código estudiantil.",
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        // Si pasa todo, guardar datos
        java.io.FileWriter writer = new java.io.FileWriter(archivo, true);
        writer.write(codigo + "," + nombre + "," + correo + "," + carrera + "," + contraseña + "\n");
        writer.close();

        javax.swing.JOptionPane.showMessageDialog(this, 
            "Registro exitoso. ¡Bienvenido/a, " + nombre + "!",
            "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
         InicioDeSesion ventana = new InicioDeSesion();
         ventana.setVisible(true);
         this.dispose();

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Error al registrar: " + e.getMessage(),
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }


        javax.swing.JOptionPane.showMessageDialog(this,"Intento de login con los datos: \nUsuario:" + CampoCódigo.getText() + "\nContraseña:" + CampoContraseña.getText(), "REGISTRO", javax.swing.JOptionPane.INFORMATION_MESSAGE );
    }//GEN-LAST:event_botonAceptarMouseClicked

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed

    }//GEN-LAST:event_botonAceptarActionPerformed

    private void IniciarSesiónMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarSesiónMouseClicked
         InicioDeSesion ventana = new InicioDeSesion();
         ventana.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_IniciarSesiónMouseClicked

    private void IniciarSesiónMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarSesiónMouseEntered
      IniciarSesión.setForeground(new Color(22, 122, 135));
    }//GEN-LAST:event_IniciarSesiónMouseEntered

    private void IniciarSesiónMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniciarSesiónMouseExited
      IniciarSesión.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_IniciarSesiónMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoCarrera;
    private javax.swing.JTextField CampoConfirmarContraseña;
    private javax.swing.JTextField CampoContraseña;
    private javax.swing.JTextField CampoCorreo;
    private javax.swing.JTextField CampoCódigo;
    private javax.swing.JLabel IniciarSesión;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel título;
    // End of variables declaration//GEN-END:variables
}
